---
title: "Clone identification"
author: "Ruben Schep"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  html_document:
    theme: journal #cerulean
    highlight: monochrome
    toc: true
    toc_float: true
    code_folding: show
  editor_options:
    chunk_output_type: console
---

# knitr document van Steensel lab

# TRIP Clone identification

# Introduction

## Description of Data
How to make a good rendering table: 
```{r table1, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
tabl <- "
| column1	|	column2	|	column3	|	
|----|----|----|
|1	|	2	|	3	|	
|a	|	b	|	c	|	
"
cat(tabl) # output the table in a format good for HTML/PDF/docx conversion
```

# Data processing
## Path, Libraries, Parameters and Useful Functions
```{r setup}
knitr::opts_chunk$set(echo = TRUE)
StartTime <-Sys.time()

# 8-digit Date tag:
Date <- substr(gsub("-","",Sys.time()),1,8) 
# libraries:
```

### Custom functions
Functions used thoughout this script.
```{r}
SetFileName <- function(filename, initials) {
  # Set filename with extension and initials to make filename with date integrated.
  filename <- substitute(filename)
  initials <- substitute(initials)
  filename <- paste0(initials, Date, filename)
  filename
}
```


## Data import
```{r Data Import}
setwd("~/mydata/EpiScreen/epigenetic-screening-on-trip-clone/Data/")

# Import data from preprocessing script
indel.data <- get(load("mt20190128_indel.data"))
findhits.data <- indel.data

outlier.df <- get(load("mt20190128_outlier.df"))
```

## Analysis
```{r Analysis}
# Divide data in 'closed', 'permissive', and 'open' barcodes (based on eyeballing)
findhits.data$chr.state <- "permissive"
findhits.data[grep("CATCCACCACACTTCA|CATTTCTGATCAATAA|ACTGTCGAGTTGTCCG|GTACCTCTCGATAGTG|TCTTTTGAGGAGCTGA|TGGCCAATATTTGTCT", findhits.data$barcode),]$chr.state <- "closed"
findhits.data[grep("AGAAAATAATATGACG|AGGGCGTAAAATATTT|ATACTATATTTAACGG|GCTAACATCACGAATC|ATATCGTTGCTGGAGA", findhits.data$barcode),]$chr.state <- "open"

# The same with outlier.df
outlier.df$chr.state <- "permissive"
outlier.df[grep("CATCCACCACACTTCA|CATTTCTGATCAATAA|ACTGTCGAGTTGTCCG|GTACCTCTCGATAGTG|TCTTTTGAGGAGCTGA|TGGCCAATATTTGTCT", outlier.df$barcode),]$chr.state <- "closed"
outlier.df[grep("AGAAAATAATATGACG|AGGGCGTAAAATATTT|ATACTATATTTAACGG|GCTAACATCACGAATC|ATATCGTTGCTGGAGA", outlier.df$barcode),]$chr.state <- "open"

outlier.df$chr.state <- "permissive"
outlier.df[grep("CATCCACCACACTTCA|CATTTCTGATCAATAA|ACTGTCGAGTTGTCCG|GTACCTCTCGATAGTG|TCTTTTGAGGAGCTGA|TGGCCAATATTTGTCT", outlier.df$barcode),]$chr.state <- "closed"
outlier.df[grep("AGAAAATAATATGACG|AGGGCGTAAAATATTT|ATACTATATTTAACGG|GCTAACATCACGAATC|ATATCGTTGCTGGAGA", outlier.df$barcode),]$chr.state <- "open"

# Find drugs that have effect on one chr.state but not on the other
# Make open, permissive & closed dfs
open.df <- outlier.df[grep("open",outlier.df$chr.state),]
permissive.df <- outlier.df[grep("permissive",outlier.df$chr.state),]
closed.df <- outlier.df[grep("closed",outlier.df$chr.state),]

# Make list with drugs that are outliers in open & closed state
x1 <- intersect(open.df$Drug, closed.df$Drug)
x2 <- intersect(open.df$Drug, permissive.df$Drug)
x3 <- intersect(closed.df$Drug, permissive.df$Drug)


# Delete these drugs from the outlier.df to keep interesting drugs
outlier.df2 <- outlier.df[!outlier.df %in% x]
xx <- outlier.df[setdiff(names(outlier.df$Drug), x)]
outlier.df2 <- unique(grep(paste(x, collapse = "|"), outlier.df$Drug, value = TRUE))


HDM.df <- findhits.data[grep("Histone demethylase|Negative control", findhits.data$Target),]
ERD.df <- indel.data[grep("Epigenetic Reader Domain|Negative control", findhits.data$Target),]


```


## Visualisation
```{r Visualization}
```

# Results
```{r}
```

# Conclusions
```{r}
```

## Exporting potential data. 
```{r}
```

# Session Info
```{r}
paste("Run time: ",format(Sys.time()-StartTime))
getwd()
date()
sessionInfo()
```

