---
title: "Figure 5 - HDAC validations"
author: "Ruben Schep"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    theme: journal #cerulean
    highlight: monochrome
    toc: true
    toc_float: true
    code_folding: show
  editor_options:
    chunk_output_type: console
---

# Setup 

```{r setup}
StartTime <-Sys.time()
Date <- substr(gsub("-","",Sys.time()),1,8)

library(knitr)
library(tidyverse)
library(ggplot2)
library(Hmisc)
library(ggpubr)
library(rstatix)
library(ggbeeswarm)
library(data.table)
library(cowplot)

## Select outdir
out.dir = paste0("figures/rs", Date, "/")
dir.create(out.dir)
opts_chunk$set(dev=c('png', 'pdf'), fig.path = file.path(out.dir))
pdf.options(useDingbats = FALSE)
```

## Functions 

```{r functions, message=FALSE, warnings=FALSE}
SetFileName <- function(filename, initials) {
  # Set filename with extension and initials to make filename with date integrated.
  filename <- substitute(filename)
  initials <- substitute(initials)
  filename <- paste0(initials, substr(gsub("-","",Sys.time()),1,8), "_", filename)
  filename
}

CorrelationDFMean <- function(data, feature_name, targets, p.value=0.001){
  hist.corr.list <- data %>% dplyr::select(feature_name, targets) %>% as.matrix() %>% rcorr(type = "spearman")
  
  histone.corr.df <- data.frame(rowname = names(hist.corr.list$r[1, -1]),
                                corr = hist.corr.list$r[1, -1],
                                pvalue = hist.corr.list$P[1, -1])
  
  return(histone.corr.df=histone.corr.df)
}


CorrelationPlotMean <- function(data, feature_name, targets, p.value=0.001, alfa = c(0.5, 1)){
  cor.df = data.frame()
  for (i in feature_name){
    corr.list <- data %>% dplyr::select(i, as.character(targets)) %>% as.matrix() %>% rcorr(type = "spearman")
    
    df <- data.frame(rowname = names(corr.list$r[1, -1]),
                     corr = corr.list$r[1, -1],
                     pvalue = corr.list$P[1, -1],
                     feature = i)
    cor.df <- rbind(cor.df, df)
  }
  p <- cor.df %>%
    transform(rowname = factor(rowname, levels = levels(targets)),
              corr = corr,
              pvalue = pvalue) %>%
    ggplot(aes(x = rowname, y = corr, fill = feature)) +
    geom_bar(stat = "identity", position = "dodge") +
    ylab(paste("Spearman correlation fold change after Vorinostat treatment")) +
    xlab("Chromatin Feature") +
    # ggtitle(paste("Repair pathways correlation with chromatin features in", condition_name, "exps")) +
    theme_bw(base_size = 16) +
    scale_y_continuous(breaks=seq(-1,1, .1)) +
    coord_flip()
  return(list(dataframe=cor.df, plot = p))
}

clustering = data.frame(row.names=c('LMNB1', 'late_replicating', 'H3K9me2',
                                    'H3K27me3', 'EZH2', 'CTCF', 'SMC3',
                                    'HDAC3', 'HDAC2', 'HDAC1', 'H3K4me1',
                                    'H3K4me2', 'H3K4me3', 'H3K27ac',
                                    'H4K5acK8ac', 'H2AFZ', 'DNAse', 'Dam', 
                                    'm5C', 'H3K79me2', 'TTseq', 'H3K36me3', 
                                    'POL2AS2', 'POL2'),
                        group=factor(c(rep('repressive', 5), rep('insulator', 2),
                                       rep('HDAC', 3), rep('euchromatin', 6),
                                       rep('accessibility', 2), 'methylation',
                                       rep('transcribing', 5)),
                                     levels=c('transcribing', 'accessibility',
                                              'methylation', 'euchromatin',
                                              'HDAC', 'insulator', 'repressive')))

cor_test <- function(y, X, left, right){
  cor_list = lapply(X, function(x){
    cor.test(x,y)
  })
  p_vec = unlist(lapply(cor_list, function(x){x$p.value}))
  cor_vec = unlist(lapply(cor_list, function(x){x$estimate}))
  p_adj = p.adjust(p_vec)
  color = ifelse(p_adj < 0.05, ifelse(cor_vec > 0, left, right),
                 'None')
  importance = abs(cor_vec)
  target=factor(colnames(X), levels=rownames(clustering))
  feature_group = clustering[colnames(X), ]
  return(list(correlation=cor_vec,importance = importance, p=p_vec,
              p_adj=p_adj, target=target, color=color,
              feature_group=feature_group))
}

get_combinations <- function(domain_vec){
  n_domain = length(domain_vec)
  get_ivec <-function (last_x, n_domain){
    if (last_x < n_domain){
      i_vec = c(0, c((last_x+1):n_domain))
    } else{
      i_vec = c(0)
    }
  }
  
  combine <- function(x_new, x_vec, n_domain){
    new_vec = c(x_vec, x_new)
    if (length(new_vec)==n_domain){
      return(new_vec)
    } else {
      i_vec = get_ivec(max(new_vec), n_domain)
      x_list = lapply(i_vec, combine, x_vec=new_vec,
                      n_domain=n_domain)
      return(do.call(rbind, x_list))
    }
  }
  
  comb_list = lapply(c(0:n_domain), combine, x_vec=c(), n_domain=n_domain)
  
  comb = do.call(rbind, comb_list)
  comb_df = unique(t(apply(comb, 1, function(x){x[order(x)]})))
  
  name_list = apply(comb_df, 1, function(x){
    name = paste(domain_vec[x], collapse='-')
    if (name == ''){
      name = 'iDomain'
    }
    return(name)
  })
  
  opt_list = lapply(domain_vec, function(d){
    apply(comb_df, 1, function(x){
      opt = domain_vec[x]
      return(d%in%opt)
    })
  })
  
  opt_df = do.call(cbind, opt_list)
  colnames(opt_df) = domain_vec
  rownames(opt_df) = name_list
  
  return(opt_df)
}

plot_comb_grid <- function(indel.dt, opt_df, domains, y_name, min_count=0,
                           max_count=Inf, group_by=NULL, color=NULL, y_plabel=c(0.15, 0.25)){
  
  opt_melt = reshape2::melt(opt_df)
  colnames(opt_melt) = c('group', 'domain', 'is_in')
  
  opt_melt$is_in = ifelse(opt_melt$is_in, 'in', 'out')
  opt_melt$domain = factor(opt_melt$domain, levels=domains)
  
  
  group_list = lapply(rownames(opt_df), function(opt_name){
    opt = opt_df[opt_name, ]
    in_vec = domains[opt]
    out_vec = domains[!opt]
    
    in_sum = rowSums(indel.dt[,..in_vec])
    out_sum = rowSums(indel.dt[,..out_vec])
    if (length(in_vec)==0){
      in_group = which(out_sum == 0)
    } else if (length(out_vec) == 0){
      in_group = which(in_sum==length(in_vec))
    } else  {
      in_group = which(in_sum == length(in_vec) & out_sum==0)
    }
    return(in_group)
  })
  
  names(group_list) = rownames(opt_df)
  for (opt_name in names(group_list)){
    i_vec = group_list[[opt_name]]
    indel.dt[i_vec, group := opt_name]
  }
  if (is.null(group_by)){
    group_count_df = data.frame(indel.dt[,table(group)])
  } else {
    group_count_df = data.frame(indel.dt[,table(group)/length(unique(get(group_by)))])
  }
  group_count_df = group_count_df[order(match(group_count_df$group, rownames(opt_df))),]
  # print(group_count_df)
  group_count_sel = group_count_df[group_count_df$Freq>=min_count,]
  group_count_sel = group_count_sel[group_count_sel$Freq<=max_count,]
  group_levels =  group_count_sel$group
  opt_sel = opt_melt[opt_melt$group %in% group_levels, ]
  
  opt_sel$group = factor(opt_sel$group, levels=group_levels)
  # print(opt_sel)
  
  indel_selection = indel.dt[group%in%group_levels, ]
  indel_selection[,group:=factor(group, levels=group_levels)]
  
  group_count_sel$group = factor(group_count_sel$group, levels=group_levels)
  
  count_plot = ggplot(group_count_sel, aes(x=group,y=1, label=Freq)) +
    geom_label() +
    theme_void()
  
  
  
  dots = ggplot(opt_sel, aes(x=group, y=domain, color=is_in)) +
    geom_point(size=2) +
    geom_line(data=opt_sel[opt_sel$is_in=='in',], aes(group=group)) +
    theme_bw() +
    scale_color_manual(values=c('in'='black', 'out'='grey70')) +
    guides(color=FALSE)  +
    geom_vline(xintercept=seq(1.5, length(unique(indel.dt$group))-0.5, 1),
               lwd=0.5, colour="grey90") +
    theme(axis.title=element_blank(),
          axis.text=element_blank(),
          axis.ticks=element_blank(),
          panel.grid.major = element_blank())
  
  symnum = list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 1),
                symbols = c("****", "***", "**", "*", ""))
  
  if (is.null(group_by)){
    level_vec = indel_selection[, levels(group)]
    wilcox_list = lapply(level_vec[level_vec!='iDomain'],
                         function(g){
                           x = indel_selection[group==g, y_name, with=F]
                           y = indel_selection[group=='iDomain', y_name,
                                               with=F]
                           w = wilcox.test(unlist(x),unlist(y))
                           return(data.table('group1'='iDomain', 'group2'=g,
                                             'p'=w$p.value))
                         })
    wilcox_dt = do.call(rbind, wilcox_list)
    wilcox_dt[,p_adj := p.adjust(p)]
    wilcox_dt[,p_label := sprintf('%.3g', p_adj)]
    wilcox_dt$y.position = seq(y_plabel[1], y_plabel[2],
                               length.out=nrow(wilcox_dt))
    
    comparisons = lapply(level_vec[level_vec!='iDomain'],
                         function(x){return(c('iDomain', x))})
    beeswarm = ggplot(indel_selection, aes_string(x='group', y=y_name)) +
      geom_quasirandom(width=0.3) +
      stat_summary(fun=median, fun.min = median,
                   fun.max = median,
                   geom="crossbar", width = 0.5,
                   color='red') +
      stat_pvalue_manual(wilcox_dt, label = "p_label")
  } else {
    wilcox_dt = indel_selection[,test_wilcox(.SD, group_by, y_name),
                                by='group']
    wilcox_dt[,p_adj:=p.adjust(p_value)]
    wilcox_dt[,p_signif:=symnum(p_adj, cutpoints=symnum$cutpoints,
                                symbols=symnum$symbols)]
    beeswarm = ggplot(indel_selection,
                      aes_string(x='group', y=y_name, color=group_by)) +
      geom_quasirandom(dodge.width=1) +
      scale_color_manual(values=color) +
      stat_summary(aes_string(group=group_by), fun.=median,
                   fun.min = median, fun.max = median,
                   geom="crossbar", width = 0.5,
                   color='red',
                   position= position_dodge(width =1)) +
      geom_text(data=wilcox_dt, aes(x=group, y=0.8, label=p_signif),
                inherit.aes=F)
  }
  
  beeswarm = beeswarm +
    theme_bw() +
    geom_vline(xintercept=seq(1.5, length(unique(indel.dt$group))-0.5, 1),
               lwd=0.5, colour="grey90") +
    theme(axis.title=element_blank(),
          axis.text.x=element_blank(),
          panel.grid.major.x = element_blank(),
          axis.ticks.x=element_blank())
  
  count = data.frame(domain=gsub('_domain', '', domains),
                     count=colSums(indel.dt[,..domains], na.rm=T))
  
  count$domain = factor(count$domain, levels=domain_levels)
  
  
  histogram = ggplot(count, aes(x=1, y=domain, label = count)) +
    geom_label() +
    theme_bw() +
    theme(plot.background = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          axis.title=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks=element_blank())
  
  empty = ggplot(data=data.frame(1,1),aes(x=1,y=1)) +
    geom_point() +
    theme_void()
  
  count_beeswarm = plot_grid(beeswarm, count_plot, ncol=1, rel_heights=c(20,1),
                             align='v', axis='lr')
  return(plot_grid(empty, beeswarm, empty, count_plot,
                   histogram, dots, nrow=3,
                   rel_widths=c(1,10), rel_heights=c(15,1,5), align='vh',
                   axis='tlbr'))
}

quantiles_95 <- function(x) {
  r <- quantile(x, probs=c(0.05, 0.25, 0.5, 0.75, 0.95))
  names(r) <- c("ymin", "lower", "middle", "upper", "ymax")
  r
}

plot_comb_grid_bothplot <- function(bix.dt, opt_df, domains, y_name, min_count=0,
                                   max_count=Inf, group_by=NULL, color=NULL){
  
  opt_melt = reshape2::melt(opt_df)
  colnames(opt_melt) = c('group', 'domain', 'is_in')
  
  opt_melt$is_in = ifelse(opt_melt$is_in, 'in', 'out')
  opt_melt$domain = factor(opt_melt$domain, levels=domains)
  
  
  group_list = lapply(rownames(opt_df), function(opt_name){
    opt = opt_df[opt_name, ]
    in_vec = domains[opt]
    out_vec = domains[!opt]
    
    in_sum = rowSums(bix.dt[,..in_vec])
    out_sum = rowSums(bix.dt[,..out_vec])
    if (length(in_vec)==0){
      in_group = which(out_sum == 0)
    } else if (length(out_vec) == 0){
      in_group = which(in_sum==length(in_vec))
    } else  {
      in_group = which(in_sum == length(in_vec) & out_sum==0)
    }
    return(in_group)
  })
  
  names(group_list) = rownames(opt_df)
  for (opt_name in names(group_list)){
    i_vec = group_list[[opt_name]]
    bix.dt[i_vec, group := opt_name]
  }
  if (is.null(group_by)){
    group_count_df = data.frame(bix.dt[,table(group)])
  } else {
    group_count_df = data.frame(bix.dt[,table(group)/length(unique(get(group_by)))])
  }
  group_count_df = group_count_df[order(match(group_count_df$group, rownames(opt_df))),]
  # print(group_count_df)
  group_count_sel = group_count_df[group_count_df$Freq>=min_count,]
  group_count_sel = group_count_sel[group_count_sel$Freq<=max_count,]
  group_levels =  group_count_sel$group
  opt_sel = opt_melt[opt_melt$group %in% group_levels, ]
  
  opt_sel$group = factor(opt_sel$group, levels=group_levels)
  # print(opt_sel)
  
  indel_selection = bix.dt[group%in%group_levels, ]
  indel_selection[,group:=factor(group, levels=group_levels)]

  group_count_sel$group = factor(group_count_sel$group, levels=group_levels)
  
  count_plot = ggplot(group_count_sel, aes(x=group,y=1, label=Freq)) +
    geom_label() +
    theme_void()
  
  
  
  dots = ggplot(opt_sel, aes(x=group, y=domain, color=is_in)) +
    geom_point(size=2) +
    geom_line(data=opt_sel[opt_sel$is_in=='in',], aes(group=group)) +
    theme_bw() +
    scale_color_manual(values=c('in'='black', 'out'='grey70')) +
    guides(color=FALSE)  +
    geom_vline(xintercept=seq(1.5, length(unique(bix.dt$group))-0.5, 1),
               lwd=0.5, colour="grey90") +
    theme(axis.title=element_blank(),
          axis.text=element_blank(),
          axis.ticks=element_blank(),
          panel.grid.major = element_blank())
  
  symnum = list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 1),
                symbols = c("****", "***", "**", "*", " "))
  
  if (is.null(group_by)){
    boxpl = ggplot(indel_selection, aes_string(x='group', y=y_name)) +
      geom_quasirandom(width=0.3) +
      stat_summary(fun=median, fun.min = median,
                   fun.max = median,
                   geom="crossbar", width = 0.5,
                   color='red') +
      stat_compare_means(aes(label = ..p.signif..),
                         symnum.args = symnum,
                         method = 'wilcox.test',
                         ref.group='iDomain')
  } else {
    
    boxpl = ggplot(indel_selection,
                   aes_string(x='group', y=y_name, color=group_by)) +
      guides(fill=F) +
      # scale_fill_manual(values=color) +
      scale_color_manual(values=color) +
      # geom_violin(position=position_dodge(width=1)) +
      geom_quasirandom(dodge.width = 1) +
      # stat_summary(fun.data = quantiles_95,
      #              geom="boxplot",
      #              position=position_dodge(width=1),
      #              width = 0.2) +
      stat_summary(fun=median, fun.min = median,
                   fun.max = median,
                   geom="crossbar", width = 0.6,
                   position=position_dodge(width=1))
  }
  boxpl = boxpl +
    theme_bw() +
    geom_vline(xintercept=seq(1.5, length(unique(bix.dt$group))-0.5, 1),
               lwd=0.5, colour="grey90") +
    theme(axis.title=element_blank(),
          axis.text.x=element_blank(),
          panel.grid.major.x = element_blank(),
          axis.ticks.x=element_blank()) +
    ylim(0, 1)
  
  
  count = data.frame(domain=gsub('_domain', '', domains),
                     count=colSums(bix.dt[,..domains], na.rm=T))
  
  count$domain = factor(count$domain, levels=domain_levels)
  
  
  histogram = ggplot(count, aes(x=1, y=domain, label = count)) +
    geom_label() +
    theme_bw() +
    theme(plot.background = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          axis.title=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks=element_blank())
  
  empty = ggplot(data=data.frame(1,1),aes(x=1,y=1)) +
    geom_point() +
    theme_void()
  
  count_beeswarm = plot_grid(boxpl, count_plot, ncol=1, rel_heights=c(20,1),
                             align='v', axis='lr')
  return(plot_grid(empty, boxpl, empty, count_plot,
                   histogram, dots, nrow=3,
                   rel_widths=c(1,10), rel_heights=c(15,1,5), align='vh',
                   axis='tlbr'))
}

plot_comb_grid_beeswarm <- function(dt, opt_df, domains, y_name, min_count=0,
                                    max_count=Inf, group_by=NULL, color=NULL, y_plabel=c(-1.5, 1.5)){
  
  opt_melt = reshape2::melt(opt_df)
  colnames(opt_melt) = c('group', 'domain', 'is_in')
  
  opt_melt$is_in = ifelse(opt_melt$is_in, 'in', 'out')
  opt_melt$domain = factor(opt_melt$domain, levels=domains)
  
  
  group_list = lapply(rownames(opt_df), function(opt_name){
    opt = opt_df[opt_name, ]
    in_vec = domains[opt]
    out_vec = domains[!opt]
    
    in_sum = rowSums(dt[,..in_vec])
    out_sum = rowSums(dt[,..out_vec])
    if (length(in_vec)==0){
      in_group = which(out_sum == 0)
    } else if (length(out_vec) == 0){
      in_group = which(in_sum==length(in_vec))
    } else  {
      in_group = which(in_sum == length(in_vec) & out_sum==0)
    }
    return(in_group)
  })
  
  names(group_list) = rownames(opt_df)
  for (opt_name in names(group_list)){
    i_vec = group_list[[opt_name]]
    dt[i_vec, group := opt_name]
  }
  if (is.null(group_by)){
    group_count_df = data.frame(dt[,table(group)])
  } else {
    group_count_df = data.frame(dt[,table(group)/length(unique(get(group_by)))])
  }
  group_count_df = group_count_df[order(match(group_count_df$group, rownames(opt_df))),]
  # print(group_count_df)
  group_count_sel = group_count_df[group_count_df$Freq>=min_count,]
  group_count_sel = group_count_sel[group_count_sel$Freq<=max_count,]
  group_levels =  group_count_sel$group
  opt_sel = opt_melt[opt_melt$group %in% group_levels, ]
  
  opt_sel$group = factor(opt_sel$group, levels=group_levels)
  # print(opt_sel)
  
  indel_selection = dt[group%in%group_levels, ]
  indel_selection[,group:=factor(group, levels=group_levels)]
  
  # wilcox_list = lapply(group_levels[group_levels!='iDomain'],
  #                      function(g){
  #                          x = indel_selection[group==g, y_name, with=F]
  #                          y = indel_selection[group=='iDomain', y_name,
  #                                              with=F]
  #                          wilcox.test(unlist(x),unlist(y))
  #                      })
  
  group_count_sel$group = factor(group_count_sel$group, levels=group_levels)
  
  count_plot = ggplot(group_count_sel, aes(x=group,y=1, label=Freq)) +
    geom_label() +
    theme_void()
  
  
  
  dots = ggplot(opt_sel, aes(x=group, y=domain, color=is_in)) +
    geom_point(size=2) +
    geom_line(data=opt_sel[opt_sel$is_in=='in',], aes(group=group)) +
    theme_bw() +
    scale_color_manual(values=c('in'='black', 'out'='grey70')) +
    guides(color=FALSE)  +
    geom_vline(xintercept=seq(1.5, length(unique(dt$group))-0.5, 1),
               lwd=0.5, colour="grey90") +
    theme(axis.title=element_blank(),
          axis.text=element_blank(),
          axis.ticks=element_blank(),
          panel.grid.major = element_blank())
  
  symnum = list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 1),
                symbols = c("****", "***", "**", "*", " "))
  
  
  if (is.null(group_by)){
    beeswarm = ggplot(indel_selection, aes_string(x='group', y=y_name)) +
      geom_quasirandom(width=0.3) +
      stat_summary(fun=median, fun.min = median,
                   fun.max = median,
                   geom="crossbar", width = 0.5,
                   color='red') +
      stat_compare_means(aes(label = ..p.signif..),
                         symnum.args = symnum,
                         method = 'wilcox.test',
                         ref.group='iDomain')
    
  } else {
    wilcox_dt = indel_selection[,test_wilcox(.SD, group_by, y_name),
                                by='group']
    wilcox_dt[,p_adj:=p.adjust(p_value)]
    wilcox_dt[,p_signif:=symnum(p_adj, cutpoints=symnum$cutpoints,
                                symbols=symnum$symbols)]
    
    
    beeswarm = ggplot(indel_selection,
                      aes_string(x='group', y=y_name, color=group_by)) +
      geom_quasirandom(dodge.width=1) +
      scale_color_manual(values=color) +
      stat_summary(aes_string(group=group_by), fun=median,
                   fun.min = median, fun.max = median,
                   geom="crossbar", width = 0.5,
                   color='red',
                   position= position_dodge(width =1)) +
      geom_text(data=wilcox_dt, aes(x=group, y=0.8, label=p_signif),
                inherit.aes=F)
    print(wilcox_dt)
  }
  beeswarm = beeswarm +
    theme_bw() +
    geom_vline(xintercept=seq(1.5, length(unique(dt$group))-0.5, 1),
               lwd=0.5, colour="grey90") +
    theme(axis.title=element_blank(),
          axis.text.x=element_blank(),
          panel.grid.major.x = element_blank(),
          axis.ticks.x=element_blank()) +
    ylim(y_plabel)
  
  count = data.frame(domain=gsub('_domain', '', domains),
                     count=colSums(dt[,..domains], na.rm=T))
  
  count$domain = factor(count$domain, levels=domain_levels)
  
  histogram = ggplot(count, aes(x=1, y=domain, label = count)) +
    geom_label() +
    theme_bw() +
    theme(plot.background = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          axis.title=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks=element_blank())
  
  empty = ggplot(data=data.frame(1,1),aes(x=1,y=1)) +
    geom_point() +
    theme_void()
  
  count_beeswarm = plot_grid(beeswarm, count_plot, ncol=1, rel_heights=c(20,1),
                             align='v', axis='lr')
  return(plot_grid(empty, beeswarm, empty, count_plot,
                   histogram, dots, nrow=3,
                   rel_widths=c(1,10), rel_heights=c(15,1,5), align='vh',
                   axis='tlbr'))
}
```


```{r}
validations_ratios = readRDS("/DATA/projects/DSBrepair/data/R/rs20210813_episcreen_2/rs20210813_episcreen_validation_ratios.RDS")
validations_indels = readRDS("/DATA/projects/DSBrepair/data/R/rs20210813_episcreen_2/rs20210813_episcreen_validation_indels.RDS")
screen_indels = readRDS("/DATA/projects/DSBrepair/data/R/rs20210813_episcreen_2/rs20210813_episcreen_ratios_split.RDS")
```


```{r plotting exploration}
vorinostat_ratios = validations_ratios %>% 
  filter(replicate == "mean" & plasmid == "LBR2") %>% 
  distinct(barcode, drug, MMEJ_MMEJNHEJ, efficiency) %>% 
  pivot_wider(names_from = drug, values_from = c(efficiency, MMEJ_MMEJNHEJ)) %>%
  mutate(diff_efficiency = efficiency_Vorinostat - efficiency_DMSO,
         ratio_efficiency = efficiency_Vorinostat/efficiency_DMSO,
         diff_MMEJ_MMEJNHEJ = MMEJ_MMEJNHEJ_Vorinostat - MMEJ_MMEJNHEJ_DMSO,
         ratio_MMEJ_MMEJNHEJ = MMEJ_MMEJNHEJ_Vorinostat/MMEJ_MMEJNHEJ_DMSO) 
  
vorinostat_ratios %<>% left_join(unique(validations_ratios[, c(1, 40:73)]), by = "barcode") %>% distinct(barcode, .keep_all = TRUE)
```

```{r ratio MMEJNHEJ vs chrom, fig.height=8, fig.width=9}
chrom.mods.cols <- seq(grep("ratio_MMEJ_MMEJNHEJ", names(vorinostat_ratios))+1, grep("H3K27me3_domain", names(vorinostat_ratios))-1)

vorinostat.hist.corr <- CorrelationDFMean(vorinostat_ratios, "diff_MMEJ_MMEJNHEJ", targets = chrom.mods.cols) %>%
  arrange(corr) %>% pull(rowname) %>% factor(.,levels = .)

lims = 1

CorrelationPlotMean(vorinostat_ratios, "diff_MMEJ_MMEJNHEJ", targets = vorinostat.hist.corr)


vorinostat_ratios %>% filter(abs(log(diff_MMEJ_MMEJNHEJ)) > .2) 
```

```{r ratio efficiency vs chrom, fig.height=8, fig.width=9}
chrom.mods.cols <- seq(grep("ratio_MMEJ_MMEJNHEJ", names(vorinostat_ratios))+1, grep("H3K27me3_domain", names(vorinostat_ratios))-1)

vorinostat.hist.corr <- CorrelationDFMean(vorinostat_ratios, "ratio_efficiency", targets = chrom.mods.cols) %>%
  arrange(corr) %>% pull(rowname) %>% factor(.,levels = .)

lims = 1

CorrelationPlotMean(vorinostat_ratios, "ratio_efficiency", targets = vorinostat.hist.corr)

vorinostat_ratios %>% filter(abs(log(ratio_efficiency)) > 2) 
```

```{r}
vorinostat_ratios %>% ggplot(., aes(diff_MMEJ_MMEJNHEJ)) + geom_density()
vorinostat_ratios %>% ggplot(., aes(ratio_MMEJ_MMEJNHEJ)) + geom_density()
vorinostat_ratios %>% ggplot(., aes(diff_efficiency)) + geom_density()
vorinostat_ratios %>% ggplot(., aes(ratio_efficiency)) + geom_density()

```

```{r}
vorinostat_ratios %>%
  dplyr::select(barcode, diff_MMEJ_MMEJNHEJ, ratio_MMEJ_MMEJNHEJ, diff_efficiency, ratio_efficiency, LMNB1, H3K4me1, POL2AS2, EZH2, H3K27ac, H3K27me3) %>%
  group_by(barcode) %>%
  gather(diff_MMEJ_MMEJNHEJ, ratio_MMEJ_MMEJNHEJ, diff_efficiency, ratio_efficiency, key = "pathway", value = "ratio") %>%
  gather(LMNB1, H3K4me1, POL2AS2, EZH2, H3K27ac, H3K27me3, key = "feature", value = "value") %>%
  ggplot(., aes(ratio, value))  +  
  geom_point() +
  geom_smooth(method= "lm") +
  theme_bw(base_size = 16) +
  stat_cor(method = "spearman") +
  facet_grid(feature ~ pathway, scales = "free")
```


```{r}
barcodes.vori = vorinostat_ratios %>% filter(ratio_MMEJ_MMEJNHEJ > 2) %>% pull(barcode)
colores <- c("wt" = "#808184", "other" = "black", "NHEJ" = "#e1251b", "MMEJ" = "#26419a", "SSTR" = "#007A4C")


validations_indels %>% 
  filter(type %in% c("grouped_indel", "core") & 
           barcode %in% barcodes.vori & 
           plasmid == "LBR2", 
         replicate == "mean") %>% 
  ggplot(., aes(mutation, freq)) + 
  geom_bar(stat = "identity", aes(fill = color)) + 
  scale_fill_manual("legend", values = colores) + 
  theme_bw() +
  scale_y_continuous(name="frequency") +
  scale_x_discrete(name="indel size", breaks = c("<-14", -7, 0, 1, ">2")) + 
  facet_grid(barcode ~ drug)

barcodes.vori = vorinostat_ratios %>% filter(ratio_MMEJ_MMEJNHEJ < 0.2) %>% pull(barcode)

validations_indels %>% 
  filter(type %in% c("grouped_indel", "core") & 
           barcode %in% barcodes.vori & 
           plasmid == "LBR2", 
         replicate == "mean") %>% 
  ggplot(., aes(mutation, freq)) + 
  geom_bar(stat = "identity", aes(fill = color)) + 
  scale_fill_manual("legend", values = colores) + 
  theme_bw() +
  scale_y_continuous(name="frequency") +
  scale_x_discrete(name="indel size", breaks = c("<-14", -7, 0, 1, ">2")) + 
  facet_grid(barcode ~ drug)


barcodes.vori = vorinostat_ratios %>% filter(abs((ratio_efficiency)) > 1.2) %>% pull(barcode)


validations_indels %>% 
  filter(type %in% c("grouped_indel", "core") & 
           barcode %in% barcodes.vori & 
           plasmid == "LBR2", 
         replicate == "mean") %>% 
  ggplot(., aes(mutation, freq)) + 
  geom_bar(stat = "identity", aes(fill = color)) + 
  scale_fill_manual("legend", values = colores) + 
  theme_bw() +
  scale_y_continuous(name="frequency") +
  scale_x_discrete(name="indel size", breaks = c("<-14", -7, 0, 1, ">2")) + 
  facet_grid(barcode ~ drug)
```


```{r}
barcodes.vori = vorinostat_ratios %>% filter(abs(diff_MMEJ_MMEJNHEJ) > .2) %>% pull(barcode)


validations_indels %>% 
  filter(type %in% c("grouped_indel", "core") & 
           barcode %in% barcodes.vori & 
           plasmid == "LBR2") %>% 
  ggplot(., aes(mutation, freq)) + 
  geom_bar(stat = "identity", aes(fill = color)) + 
  scale_fill_manual("legend", values = colores) + 
  theme_bw() +
  scale_y_continuous(name="frequency") +
  scale_x_discrete(name="indel size", breaks = c("<-14", -7, 0, 1, ">2")) + 
  facet_grid(barcode ~ drug)


barcodes.vori = vorinostat_ratios %>% filter(abs(diff_efficiency) > .2) %>% pull(barcode)


validations_indels %>% 
  filter(type %in% c("grouped_indel", "core") & 
           barcode %in% barcodes.vori & 
           plasmid == "LBR2") %>% 
  ggplot(., aes(mutation, freq)) + 
  geom_bar(stat = "identity", aes(fill = color)) + 
  scale_fill_manual("legend", values = colores) + 
  theme_bw() +
  scale_y_continuous(name="frequency") +
  scale_x_discrete(name="indel size", breaks = c("<-14", -7, 0, 1, ">2")) + 
  facet_grid(barcode ~ drug)


screen_indels %>% filter(type %in% c("grouped_indel", "core") & drug == "Barasertib (AZD1152-HQPA)") %>% ggplot(.,
                                                                         aes(mutation, freq_split, color = color)) +
    geom_quasirandom() +
    theme_bw(base_size = 18) +
    ylim(0, 1) +
    theme(legend.position = c(0.1, 0.8)) +
    scale_color_manual("legend", values = colore)  +
    scale_y_continuous(name="frequency") +
    scale_x_discrete(name="indel size") + facet_wrap(. ~ exp)
```

## Affected reporters
```{r}
barcde_all_reps = validations_ratios %>% 
  filter(replicate != "mean" & plasmid == "LBR2") %>% 
  distinct(barcode, replicate, drug) %>% 
  group_by(barcode) %>%
  summarise(bccount = n()) %>% 
  filter(bccount == 6) %>%
  pull(barcode)
  

barcde_2_reps = validations_ratios %>% 
  filter(replicate != "mean" & plasmid == "LBR2") %>% 
  distinct(barcode, replicate, drug) %>% 
  group_by(barcode) %>%
  summarise(bccount = n()) %>% 
  filter(bccount >= 4) %>%
  pull(barcode)
  
vorinostat_reps_ratios = validations_ratios %>% 
  filter(replicate != "mean" & plasmid == "LBR2", barcode %in% barcde_all_reps) %>% 
  distinct(barcode, drug, MMEJ_MMEJNHEJ, efficiency, replicate) %>%
  group_by(barcode, drug) %>%
  pivot_wider(names_from = drug, values_from = c(efficiency, MMEJ_MMEJNHEJ)) %>%
  mutate(diff_efficiency = efficiency_Vorinostat - efficiency_DMSO,
         ratio_efficiency = efficiency_Vorinostat/efficiency_DMSO,
         diff_MMEJ_MMEJNHEJ = MMEJ_MMEJNHEJ_Vorinostat - MMEJ_MMEJNHEJ_DMSO,
         ratio_MMEJ_MMEJNHEJ = MMEJ_MMEJNHEJ_Vorinostat/MMEJ_MMEJNHEJ_DMSO) 


signif_IPRs_full_tib = validations_ratios %>% 
  filter(replicate != "mean" & plasmid == "LBR2" & barcode %in% barcde_all_reps) %>% 
  distinct(barcode, drug, MMEJ_MMEJNHEJ, replicate) %>%
  group_by(barcode)  %>%
  t_test(MMEJ_MMEJNHEJ ~ drug, paired = TRUE) %>%
  add_significance()

signif_IPRs_tib = validations_ratios %>% 
  filter(replicate != "mean" & plasmid == "LBR2" & barcode %in% barcde_all_reps) %>% 
  distinct(barcode, drug, MMEJ_MMEJNHEJ, replicate) %>%
  group_by(barcode)  %>%
  t_test(MMEJ_MMEJNHEJ ~ drug, paired = TRUE) %>%
  add_significance() %>% 
  distinct(barcode, p.signif, p)

signif_bcs = signif_IPRs_full_tib %>% filter(p < 0.001) %>% pull(barcode)


```
```{r}
validations_ratios %>% 
  filter(plasmid == "LBR2") %>%
  mutate(signif = ifelse(barcode %in% signif_bcs, "p > 0.05", "n.s.")) %>% 
  select(barcode, drug, sum_bc_reads, signif, replicate, pool) %>%
  ggplot(., aes(signif, log(sum_bc_reads), color = pool)) + geom_beeswarm() + facet_grid(replicate ~ drug)

validations_ratios %>% 
  filter(plasmid == "LBR2") %>%
  mutate(signif = ifelse(barcode %in% signif_bcs, "p > 0.05", "n.s.")) %>% 
  select(barcode, drug, MMEJ, signif, replicate, pool) %>%
  ggplot(., aes(signif, MMEJ, color = pool)) + geom_beeswarm() + facet_grid(replicate ~ drug)

validations_ratios %>% 
  filter(plasmid == "LBR2") %>%
  mutate(signif = ifelse(barcode %in% signif_bcs, "p > 0.05", "n.s.")) %>% 
  select(barcode, drug, NHEJ, signif, replicate, pool) %>%
  ggplot(., aes(signif, NHEJ, color = pool)) + geom_beeswarm() + facet_grid(replicate ~ drug)


validations_ratios %>%
  ggplot(., aes(pool, cells)) + geom_beeswarm() + facet_grid(replicate ~ drug) + ylim(0, 100)


validations_ratios %>% 
  mutate(signif = ifelse(barcode %in% signif_bcs, "p > 0.05", "n.s.")) %>% 
  select(barcode, drug, NHEJ, sum_bc_reads, replicate) %>%
  ggplot(., aes(sum_bc_reads, NHEJ)) + geom_point() + facet_grid(replicate ~ drug)

validations_ratios %>% 
  mutate(signif = ifelse(barcode %in% signif_bcs, "p > 0.05", "n.s.")) %>% 
  select(barcode, drug, NHEJ, MMEJ, replicate, plasmid) %>%
  ggplot(., aes(MMEJ, NHEJ, color = plasmid)) + geom_point() + facet_grid(replicate ~ drug)
```


```{r}
vorinostat_ratios_signif_subsample = validations_ratios %>% filter(replicate != "mean" & plasmid == "LBR2" & barcode %in% sample(signif_bcs, 10)) %>% group_by(barcode)
vorinostat_ratios_signif = validations_ratios %>% filter(replicate != "mean" & plasmid == "LBR2" & barcode %in% signif_bcs) %>% group_by(barcode)


vorinostat_ratios_signif %>% ggplot(., aes(drug, MMEJ_MMEJNHEJ)) + 
  geom_jitter() + 
  facet_wrap(. ~ barcode) +
  stat_compare_means(paired = TRUE)

p = ggboxplot(vorinostat_ratios_signif, x = "drug", y = "MMEJ_MMEJNHEJ",
          color = "drug", palette = "jco",
          add = "jitter",
          facet.by = "barcode",
          line.color = "gray", line.size = 0.4,)
# Use only p.format as label. Remove method name.
p + stat_compare_means(label = "p.format", paired = T, method = "t.test")
```


# Are significant sites enriched in specific regions?
```{r}
chrom.mods.cols <- seq(grep("binsize", names(validations_ratios))+1, grep("H3K27me3_domain", names(validations_ratios))-1)
chrom.mods.names <- names(validations_ratios)[chrom.mods.cols]

chroms_signif_bcs = validations_ratios %>% 
  mutate(signif = ifelse(barcode %in% signif_bcs, "p > 0.05", "n.s.")) %>% 
  select(barcode, drug, chrom.mods.cols, signif) %>%
  unique() %>%
  pivot_longer(chrom.mods.names, names_to = "feature")

chroms_signif_bcs %>% ggplot(., aes(signif, value, color = signif)) + geom_quasirandom() + facet_wrap(. ~ feature, scales = "free_y")
```


# Are significant sites enriched in specific domains?
```{r}
chrom.mods.cols <- seq(grep("binsize", names(validations_ratios))+1, grep("H3K27me3_domain", names(validations_ratios))-1)
chrom.mods.names <- names(validations_ratios)[chrom.mods.cols]

chroms_signif_bcs = validations_ratios %>% 
  mutate(signif = ifelse(barcode %in% signif_bcs, "p > 0.05", "n.s.")) %>% 
  select(barcode, drug, chrom.mods.cols, signif) %>%
  unique() %>%
  pivot_longer(chrom.mods.names, names_to = "feature")

chroms_signif_bcs %>% ggplot(., aes(signif, value, color = signif)) + geom_quasirandom() + facet_wrap(. ~ feature, scales = "free_y")
```

```{r Fig6A, fig.height=5, fig.width=7}
domain_levels = c('late_replicating', 'LAD', 'H3K9me2', 'H3K27me3', 'DHS')

domains = paste0(domain_levels, '_domain')

indel.dt = vorinostat_ratios %>%
  filter(!is.na(diff_MMEJ_MMEJNHEJ)) %>%
  dplyr::select(barcode, diff_MMEJ_MMEJNHEJ, domains) %>%
  distinct(barcode, .keep_all = TRUE) %>%
  data.table()

dim(indel.dt)


indel.dt[indel.dt=='iDomain'] <- 0
indel.dt[indel.dt=='Domain'] <- 1
indel.dt[indel.dt=='DHS'] <- 1

indel.dt[is.na(LAD_domain), LAD_domain:=0]
indel.dt[is.na(DHS_domain), DHS_domain:=0]

indel.dt[, (domains) := lapply(.SD, as.numeric), .SDcols = domains]

colnames(indel.dt) = gsub('_domain', '', colnames(indel.dt))

opt_df = get_combinations(domain_levels)

# Ratio of SSTR vs MME
plot_comb_grid_beeswarm(indel.dt, opt_df,
                        domain_levels, 'diff_MMEJ_MMEJNHEJ', min_count = 10, y_plabel=c(-3, 3))

k27me3 = indel.dt %>% filter(late_replicating == 0, 
                             LAD == 0,
                             H3K9me2 == 0,
                             H3K27me3 == 1,
                             DHS == 0) %>% 
  pull(diff_MMEJ_MMEJNHEJ)

hetcomb = indel.dt %>% filter(late_replicating == 1, 
                              LAD == 1,
                              H3K9me2 == 1,
                              H3K27me3 == 0,
                              DHS == 0) %>% 
  pull(diff_MMEJ_MMEJNHEJ)

idomain = indel.dt %>% filter(late_replicating == 0, 
                              LAD == 0,
                              H3K9me2 == 0,
                              H3K27me3 == 0,
                              DHS == 0) %>% 
  pull(diff_MMEJ_MMEJNHEJ)

DHS = indel.dt %>% filter(late_replicating == 0, 
                          LAD == 0,
                          H3K9me2 == 0,
                          H3K27me3 == 0,
                          DHS == 1) %>% 
  pull(diff_MMEJ_MMEJNHEJ)

wilcox.test(idomain, k27me3, alternative = "greater")
wilcox.test(idomain, hetcomb, alternative = "two.sided")
wilcox.test(idomain, DHS, alternative = "less")
```

