---
title: "Scratch Code"
author: "Ruben Schep"
date: "1/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Scratch chunks
```{r correlation fig S1}
# C: Correlation between technical replicates efficiency
techn_repl <- screen_ratios_tib %>%
  filter(sample %in% c("drug", "Negative Control") & conc_char == "1 µM") %>%
  dplyr::distinct(freqCut_norm, drug, tech, replicate, conc_char, sample, IPR) %>%
  mutate(freqCut_norm = log2(ave(freqCut_norm, drug, tech, replicate, conc_char, IPR, FUN = mean))) %>%
  unique() %>%
  mutate(rep = paste(replicate, tech, sep = "_")) %>%
  filter(!between(freqCut_norm, -0.05, 0.05)) %>%
  dplyr::select(-replicate, -tech) %>%
  spread(rep, freqCut_norm) %>%
  na.omit()

ggpairs(techn_repl %>% 
       # filter(IPR == "IPR14") %>% 
       # filter(drug %in% c("Vorinostat (SAHA, MK0683)", "Scriptaid",   "Decitabine" , "(+)-JQ1" ,  "PCI-24781 (Abexinostat)")) %>%
          dplyr::select(contains("E1")),
               upper = list(continuous = corColor),
               lower = list(continuous = function(data, mapping, ...) {
                   ggally_points(data = data, mapping = mapping, alpha = 0.6, size = 0.5) +
                   geom_abline(slope = 1, lty = "dashed", col = "red")}),
               diag = list(continuous = function(data, mapping, ...) {
                   ggally_densityDiag(data = data, mapping = mapping, alpha = 0.3, fill = "red")})) +
  # xlim(.4, .7) + 
  xlab("Cutting efficiency") +
  ylab("Cutting efficiency")
```

```{r heatmaps Fig2}
# Generate heatmap: select top 15 drugs (highest change at any IPR) per concentration
eff.data.heatmap <- screen_ratios_tib %>%
  filter(sample == "drug" | drug == "DMSO") %>%
  distinct(conc_char, replicate,drug, IPR, freqCut_norm_mean, freqCut_norm)


eff.data.heatmap2 <- eff.data.heatmap %>%
  dplyr::select(-freqCut_norm_mean) %>%
  mutate(freqCut_norm = ave(freqCut_norm, conc_char, drug, replicate, IPR, FUN = mean)) %>%
  distinct() %>%
  mutate(freqCut_norm = log2(freqCut_norm)) %>%
  mutate(mod = Mod(freqCut_norm)) %>%
  mutate(max = ave(mod, drug, conc_char, replicate, FUN = max)) %>%
  dplyr::select(-mod) %>%
  spread(IPR, freqCut_norm) %>%
  mutate(conc_rep = paste(conc_char, replicate, sep = " ")) %>%
  group_by(conc_rep) %>%
  top_n(25, max) %>%
  ungroup() %>%
  dplyr::select(-max)

breaks <- seq(-0.2, 0.2, 0.004)

# eff.data.heatmap2 %<>% mutate(conc_rep = paste(conc_char, replicate, sep = " "))

for (i in unique(eff.data.heatmap2$conc_rep)) {
  pheatmap(as.matrix(eff.data.heatmap2[eff.data.heatmap2$conc_rep == i,] %>%
                       column_to_rownames('drug') %>%
                       dplyr::select(contains('IPR')) %>%
                       t()),
           border_color = "white",
           cellwidth = 12,
           cellheight = 12,
           breaks = breaks,
           cluster_rows = F,
           main = paste('efficiency change, concentration =', i),
           annotation_col = target,
           annotation_row = chromatin,
           color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdBu")))(100),
           annotation_colors = annotation_colors_scr, annotation_legend = T)
}
```

```{r distribution of the MMEJ score in the controls}
mmejscore_DMSO_matrix_list = screen_indel_split_tib %>%  
  filter(drug == "DMSO") %>%
  mutate(ID = gsub("^E.*_.*_([12]_...)$", "\\1\\2", ID)) %>% 
  distinct(ID, MMEJscore_split, replicate, tech, concentration, barcode) %>%
  pivot_wider(names_from = c("replicate", "tech", "concentration"), 
              values_from = "MMEJscore_split") %>%
  group_split(barcode, .keep = FALSE)

mmejscore_DMSO_matrix_list_new = lapply(mmejscore_DMSO_matrix_list, '[', -1)

# MMEJscoreDMSOvar = mmejscore_DMSO_matrix %>%
#   rownames_to_column(var = "ID") %>%
#   pivot_longer(cols = starts_with("E"), names_to = "rep") %>%
#   group_by(rep)

sep_conc = screen_indel_split_tib %>%  
  filter(drug == "DMSO") %>%
  mutate(ID = gsub("^E.*_(.*_.*)_[12]_...$", "\\1", exp),
         plates = paste(replicate, tech, concentration, sep = "_")) %>% 
  distinct(ID,plates, freqCut_split, MMEJscore_split, replicate, tech, concentration, barcode)

for (i in unique(sep_conc$barcode)) {
  btest = bartlett.test(MMEJscore_split ~ plates, data = filter(sep_conc, barcode == i))
  print(btest)
}

sep_conc %>% 
  filter(barcode == "ACCCCTAAAGGCGCTG") %>% 
  ggplot(., aes(plates, MMEJscore_split)) + geom_jitter()

sep_conc %>% 
  filter(barcode == "ACCCCTAAAGGCGCTG") %>% 
  ggplot(., aes(plates, freqCut_split)) + geom_jitter()

sep_conc %>%  
  ggplot(., aes(plates, freqCut_split, color = barcode)) + geom_jitter()

sep_conc %>%  
  ggplot(., aes(plates, MMEJscore_split, color = barcode)) + geom_jitter()

comb_conc = screen_indel_split_tib %>%  
  filter(drug == "DMSO") %>%
  mutate(ID = gsub("^E.*_(.*_.*)_[12]_...$", "\\1", exp),
         plates = paste(replicate, tech, sep = "_")) %>% 
  distinct(ID,plates, freqCut_split, MMEJscore_split, replicate, tech, barcode)

for (i in unique(comb_conc$barcode)) {
  btest = bartlett.test(MMEJscore_split ~ plates, data = filter(comb_conc, barcode == i))
  print(btest)
  }
  
comb_conc %>% 
  filter(barcode == "ACCCCTAAAGGCGCTG") %>% 
  ggplot(., aes(plates, MMEJscore_split)) + geom_jitter()

comb_conc %>%  
  ggplot(., aes(plates, freqCut_split, color = barcode)) + geom_jitter()

comb_conc %>%  
  ggplot(., aes(plates, MMEJscore_split, color = barcode)) + geom_jitter()

mmejscore_DMSO_tib = screen_indel_split_tib %>%  
  filter(drug == "DMSO") %>%
  mutate(ID = gsub("^E.*_(.*_.*)_[12]_...$", "\\1", exp)) %>%
  distinct(ID, MMEJscore_split, replicate, tech, concentration, drug, barcode)

mmejscore_DMSO_tib %>% 
  ggplot(., aes(ID, MMEJscore_split)) + 
  geom_jitter() + 
  facet_grid(barcode ~ replicate, scales = "free_y")
```


```{r}
# For MMEJ z-score
mmejzscore_matrix = screen_indel_split_tib %>%  
  filter(sample == "drug") %>%
  mutate(ID = paste(gsub("^E.*_(.*_[12]_...)$", "\\1\\2", ID), barcode, sep = "_")) %>% 
  distinct(ID, MMEJ_zscore_split, replicate, tech) %>%
  pivot_wider(., names_from = c("replicate", "tech"), values_from = "MMEJ_zscore_split") %>%
  column_to_rownames(., var = "ID")
# 
chart.Correlation(mmejzscore_matrix, histogram=TRUE, pch=19)

# For standard MMEJ score
mmejscore_matrix = screen_indel_split_tib %>%  
  filter(sample == "drug") %>%
  mutate(ID = paste(gsub("^E.*_(.*_[12]_...)$", "\\1\\2", ID), barcode, sep = "_")) %>% 
  distinct(ID, MMEJscore_split, replicate, tech) %>%
  pivot_wider(., names_from = c("replicate", "tech"), values_from = "MMEJscore_split") %>%
  column_to_rownames(., var = "ID")
# 
chart.Correlation(mmejscore_matrix, histogram=TRUE, pch=19)

MMEJscorevar = mmejscore_matrix %>%
  rownames_to_column(var = "ID") %>%
  pivot_longer(.,cols = starts_with("E"), names_to = "rep") %>%
  group_by(rep)

MMEJscorevar %>%
  summarise(
    count = n(),
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE))
  

screen.indel.dt %>% 
  filter(sample == "drug" & replicate == "E1504") %>% 
  distinct(barcode, tech, ID, freqCut_norm_split) %>% 
  mutate(bc_ID = paste(ID, barcode, sep = "_")) %>% select(-barcode, -ID) %>% 
  pivot_wider(., names_from = tech, values_from = freqCut_norm_split) %>%
  column_to_rownames(., var = "bc_ID") %>% 
  chart.Correlation(., histogram=TRUE, pch=19)

screen.indel.dt %>% 
  filter(sample == "drug" & replicate == "E177") %>% 
  distinct(barcode, tech, ID, freqCut_norm_split) %>% 
  mutate(bc_ID = paste(ID, barcode, sep = "_")) %>% select(-barcode, -ID) %>% 
  pivot_wider(., names_from = tech, values_from = freqCut_norm_split) %>%
  column_to_rownames(., var = "bc_ID") %>% 
  chart.Correlation(., histogram=TRUE, pch=19)

screen.indel.dt %>% 
  filter(sample == "drug" & replicate == "E177") %>% 
  distinct(barcode, tech, ID, freqCut) %>% 
  mutate(bc_ID = paste(ID, barcode, sep = "_")) %>% select(-barcode, -ID) %>% 
  pivot_wider(., names_from = tech, values_from = freqCut) %>%
  column_to_rownames(., var = "bc_ID") %>% 
  chart.Correlation(., histogram=TRUE, pch=19)


# Compute the analysis of variance
res.aov <- aov(value ~ rep, data = MMEJscorevar)
# Summary of the analysis
summary(res.aov)

# Compute the analysis of variance
res.aov <- aov(value ~ rep, data = filter(MMEJscorevar, grepl("E177", rep)))
# Summary of the analysis
summary(res.aov)

# Compute the analysis of variance
res.aov <- aov(value ~ rep, data = filter(MMEJscorevar, grepl("E1504", rep)))
# Summary of the analysis
summary(res.aov)

fligner.test(value ~ rep, data = MMEJscorevar)
fligner.test(value ~ rep, data = filter(MMEJscorevar, grepl("E177", rep)))
fligner.test(value ~ rep, data = filter(MMEJscorevar, !grepl("E177", rep))) 

```


```{r}
screen_indels_tib %>% 
  filter(drug == "Barasertib (AZD1152-HQPA)", conc_char == "1 µM", type %in% c("core", "grouped_indel")) %>% 
  ggplot(., aes(mutation, freq_split , color = color)) +
    geom_quasirandom() +
    theme_bw(base_size = 18) +
    ylim(0, 1) +
    theme(legend.position = c(0.1, 0.8)) +
    scale_y_continuous(name="frequency") +
    scale_x_discrete(name="indel size") + 
  facet_grid(tech ~ replicate)
```


## Plotting for B4 meeting
Data loaded from Figure 1 script

```{r}
cols = c("100 nM  < 0.05 p.val" = "gray40", 
         "100 nM N.S." =  "gray90",
         "1 µM  < 0.05 p.val" = "gray20", 
         "1 µM N.S." =   "gray80",
         "10 µM  < 0.05 p.val" = "black", 
         "10 µM N.S." = "gray70")

indel.data %>%
  filter(sample == "drug") %>%
  distinct(mean_eff_zscore_comb , IPR, drug, conc_char, sample) %>%
  mutate(signif = ifelse(Mod(mean_eff_zscore_comb) > 1.96, " < 0.05 p.val", "N.S."),
         signif_col = paste(conc_char, signif),
          IPR = factor(gsub("IPR", "", IPR), levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19")),
         conc_char = factor(conc_char, levels = c("100nM", "1 µM", "10 µM"))) %>%
  ggplot(.,
       aes(x = IPR, y = mean_eff_zscore_comb, 
           color = signif_col, 
           group = conc_char)) +
  geom_quasirandom(dodge.width = 0.75) +
  geom_hline(linetype = "dashed", yintercept = 1.96) +
  geom_hline(linetype = "dashed", yintercept = -1.96) +
  scale_color_manual(values = cols) +
  theme_bw(base_size = 16)
```

```{r}
indel.data %>%
  filter(sample == "drug") %>%
  distinct(MMEJ_zscore_comb , IPR, drug, conc_char, sample) %>%
  mutate(signif = ifelse(Mod(MMEJ_zscore_comb) > 1.96, " < 0.05 p.val", "N.S."),
         signif_col = factor(paste(conc_char, signif), 
                             levels = c("100 nM  < 0.05 p.val", 
                                        "1 µM  < 0.05 p.val", 
                                        "10 µM  < 0.05 p.val", 
                                        "100 nM N.S.",
                                        "1 µM N.S.",
                                        "10 µM N.S.")),
         IPR = factor(gsub("IPR", "", IPR), levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19")),
         conc_char = factor(conc_char, levels = c("100nM", "1 µM",  "10 µM"))) %>%
  arrange(conc_char) %>%
  ggplot(.,
         aes(x = IPR, y = MMEJ_zscore_comb, 
             color = signif_col, 
             group = conc_char)) +
  geom_quasirandom(dodge.width = 0.75) +
  geom_hline(linetype = "dashed", yintercept = 1.96) +
  geom_hline(linetype = "dashed", yintercept = -1.96) +
  scale_color_manual(values = cols) +
  theme_bw(base_size = 16)

signif_col
```


```{r}
# Generate heatmap: select top 15 drugs (highest change at any IPR) per concentration
eff.data.heatmap <- indel.data %>%
  #filter(target != "Aurora Kinase") %>%
  filter(sample == "drug" | drug %in% c("DMSO")) %>%
  #filter(Mod(eff_zscore_pooled_global_comb) >= 1.645) %>%  # we could also choose to display all drugs that have significant global hits
  distinct(conc_char,drug, IPR, MMEJ_zscore_comb  )

## Select drugs that have a large effect size in at least one location (some drugs might have a small global effect size, but large local)
eff.data.heatmap2 <- eff.data.heatmap %>%
  mutate(mod = Mod(MMEJ_zscore_comb  )) %>%
  mutate(max = ave(mod, drug, conc_char, FUN = max)) %>%
  filter(max > 2.58) %>% # p < 0.05
  dplyr::select(-mod, -max) %>%
  spread(IPR, MMEJ_zscore_comb)

breaks <- seq(-15, 15, 0.01)
scale_colors = colorRampPalette(rev(brewer.pal(n = 7, name = "RdBu")))(length(breaks))
scale_colors[between(breaks, -1.96, 1.96)] <- "gray80"

for (i in unique(eff.data.heatmap2$conc_char)) {
  pheatmap(as.matrix(eff.data.heatmap2[eff.data.heatmap2$conc_char == i,] %>%
                       column_to_rownames('drug') %>%
                       dplyr::select(contains('IPR')) %>%
                       t()),
           border_color = "white",
           cellwidth = 12,
           cellheight = 12,
           breaks = breaks,
           cluster_rows = F,
           main = paste('MMEJ ratio change, concentration =', i),
           annotation_col = target,
           annotation_row = chromatin,
           color = scale_colors,
           annotation_colors = annotation_colors_scr, annotation_legend = T)
}
```


```{r}
# Generate heatmap: select top 15 drugs (highest change at any IPR) per concentration
eff.data.heatmap <- indel.data %>%
  #filter(target != "Aurora Kinase") %>%
  filter(sample == "drug" | drug %in% c("DMSO", "DNA-PKi")) %>%
  #filter(Mod(eff_zscore_pooled_global_comb) >= 1.645) %>%  # we could also choose to display all drugs that have significant global hits
  distinct(conc_char,drug, IPR, mean_eff_zscore_comb )

## Select drugs that have a large effect size in at least one location (some drugs might have a small global effect size, but large local)
eff.data.heatmap2 <- eff.data.heatmap %>%
  mutate(mod = Mod(mean_eff_zscore_comb   )) %>%
  mutate(max = ave(mod, drug, conc_char, FUN = max)) %>%
  filter(max > 2.58) %>% # p < 0.05
  dplyr::select(-mod, -max) %>%
  spread(IPR, mean_eff_zscore_comb  )

breaks <- seq(-10, 10, 0.01)

for (i in unique(eff.data.heatmap2$conc_char)) {
  pheatmap(as.matrix(eff.data.heatmap2[eff.data.heatmap2$conc_char == i,] %>%
                       column_to_rownames('drug') %>%
                       dplyr::select(contains('IPR')) %>%
                       t()),
           border_color = "white",
           cellwidth = 12,
           cellheight = 12,
           breaks = breaks,
           cluster_rows = F,
           main = paste('Indel rate z-score, concentration =', i),
           annotation_col = target,
           annotation_row = chromatin,
           color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdBu")))(length(breaks)),
           annotation_colors = annotation_colors_scr, annotation_legend = T)
}
```


```{r}
mut.data = readRDS("/DATA/projects/DSBrepair/data/R/rs20220122_episcreen/rs20220122_episcreen_mutations.RDS") 

mut.data.filt = mut.data %>% 
  filter(drug %in% c("Vorinostat (SAHA, MK0683)", "PCI-24781 (Abexinostat)","DMSO") & conc_char == "100 nM" & type %in% c("core", "grouped_indel"), IPR %in% c("IPR16", "IPR10")) %>% 
  distinct(IPR, mutation, color, type, drug, freq_mean, freq_sd)

colores <- c("wt" = "#808184", "other" = "black", "NHEJ" = "#e1251b", "MMEJ" = "#26419a", "SSTR" = "#007A4C")


p <- ggplot(mut.data.filt, 
            aes(mutation, freq_mean)) + 
  geom_bar(stat = "identity", aes(fill = color)) + 
  scale_fill_manual("legend", values = colores) + 
  theme_bw() +
  scale_y_continuous(name="frequency") +
  scale_x_discrete(name="indel size", breaks = c("<-14", -7, 0, 1, ">2")) +
  geom_errorbar(aes(ymin=freq_mean-freq_sd, ymax=freq_mean+freq_sd), width=.2,
                position=position_dodge(.9)) 
p + facet_grid(IPR ~ drug)

mut.data.filt = mut.data %>% 
  filter(drug %in% c("Vorinostat (SAHA, MK0683)", "PCI-24781 (Abexinostat)","DMSO") & conc_char == "100 nM" & type %in% c("core", "grouped_indel"), IPR %in% c("IPR16", "IPR10")) %>% 
  distinct(IPR, mutation, color, type, drug, freq_mean_rep, freq_sd_rep, replicate)

colores <- c("wt" = "#808184", "other" = "black", "NHEJ" = "#e1251b", "MMEJ" = "#26419a", "SSTR" = "#007A4C")


p <- ggplot(mut.data.filt, 
            aes(mutation, freq_mean_rep)) + 
  geom_bar(stat = "identity", aes(fill = color)) + 
  scale_fill_manual("legend", values = colores) + 
  theme_bw() +
  scale_y_continuous(name="frequency") +
  scale_x_discrete(name="indel size", breaks = c("<-14", -7, 0, 1, ">2")) +
  geom_errorbar(aes(ymin=freq_mean_rep-freq_sd_rep, ymax=freq_mean_rep+freq_sd_rep), width=.2,
                position=position_dodge(.9)) 
p + facet_grid(IPR + replicate ~ drug)

mut.data %>% pull(drug) %>% unique() %>% .[grepl("Bara", .)]


mut.data.filt = mut.data %>% 
  filter(drug %in% c("Barasertib (AZD1152-HQPA)", "2-Methoxyestradiol (2-MeOE2)","DMSO") & conc_char == "100 nM" & type %in% c("core", "grouped_indel"), IPR %in% c("IPR16")) %>% 
  distinct(IPR, mutation, color, type, drug, freq_mean_rep, freq_sd_rep, replicate)

colores <- c("wt" = "#808184", "other" = "black", "NHEJ" = "#e1251b", "MMEJ" = "#26419a", "SSTR" = "#007A4C")


p <- ggplot(mut.data.filt, 
            aes(mutation, freq_mean_rep)) + 
  geom_bar(stat = "identity", aes(fill = color)) + 
  scale_fill_manual("legend", values = colores) + 
  theme_bw() +
  scale_y_continuous(name="frequency") +
  scale_x_discrete(name="indel size", breaks = c("<-14", -7, 0, 1, ">2")) +
  geom_errorbar(aes(ymin=freq_mean_rep-freq_sd_rep, ymax=freq_mean_rep+freq_sd_rep), width=.2,
                position=position_dodge(.9)) 
p + facet_grid(IPR + replicate ~ drug)

```


```{r}
validation_indels_tib %>% filter(replicate == "mean" & plasmid == "LBR2") %>% distinct(barcode, drug, NHEJ_MMEJ) %>% pivot_wider(names_from = drug, values_from = NHEJ_MMEJ) %>%
  mutate(log2dist_mmej = log2(Vorinostat)/log2(DMSO)) %>% ggplot(.) + geom_density(aes(log2dist_mmej))

validation_indels_tib %>% filter(replicate == "mean" & plasmid == "LBR2") %>% distinct(barcode, drug, MMEJ_NHEJ) %>% pivot_wider(names_from = drug, values_from = MMEJ_NHEJ) %>%
  mutate(log2dist_mmej = log2(Vorinostat)/log2(DMSO)) %>% ggplot(.) + geom_density(aes(log2dist_mmej))

```


```{r}
indel.data  %>% 
  select(barcode, drug, conc_char, target,mean_eff_zscore_comb, all_of(chromatin.features)) %>% 
  filter(grepl("Mocet", drug), conc_char == "100 nM") %>% 
  pivot_longer(cols = all_of(chromatin.features), names_to = "feature", values_to = "zscore") %>%
  ggplot(., aes(zscore  
                ,mean_eff_zscore_comb)) + 
  geom_point(mapping =  aes(color = abs(mean_eff_zscore_comb) > 1.96)) +
  stat_cor(method = "spearman") + 
  geom_smooth(method = "lm") + 
  theme_bw() +
  facet_wrap(. ~ feature)
```
