---
title: "Scratch Code"
author: "Ruben Schep"
date: "1/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Scratch chunks
```{r correlation fig S1}
# C: Correlation between technical replicates efficiency
techn_repl <- screen_ratios_tib %>%
  filter(sample %in% c("drug", "Negative Control") & conc_char == "1 µM") %>%
  dplyr::distinct(freqCut_norm, drug, tech, replicate, conc_char, sample, IPR) %>%
  mutate(freqCut_norm = log2(ave(freqCut_norm, drug, tech, replicate, conc_char, IPR, FUN = mean))) %>%
  unique() %>%
  mutate(rep = paste(replicate, tech, sep = "_")) %>%
  filter(!between(freqCut_norm, -0.05, 0.05)) %>%
  dplyr::select(-replicate, -tech) %>%
  spread(rep, freqCut_norm) %>%
  na.omit()

ggpairs(techn_repl %>% 
       # filter(IPR == "IPR14") %>% 
       # filter(drug %in% c("Vorinostat (SAHA, MK0683)", "Scriptaid",   "Decitabine" , "(+)-JQ1" ,  "PCI-24781 (Abexinostat)")) %>%
          dplyr::select(contains("E1")),
               upper = list(continuous = corColor),
               lower = list(continuous = function(data, mapping, ...) {
                   ggally_points(data = data, mapping = mapping, alpha = 0.6, size = 0.5) +
                   geom_abline(slope = 1, lty = "dashed", col = "red")}),
               diag = list(continuous = function(data, mapping, ...) {
                   ggally_densityDiag(data = data, mapping = mapping, alpha = 0.3, fill = "red")})) +
  # xlim(.4, .7) + 
  xlab("Cutting efficiency") +
  ylab("Cutting efficiency")
```

```{r heatmaps Fig2}
# Generate heatmap: select top 15 drugs (highest change at any IPR) per concentration
eff.data.heatmap <- screen_ratios_tib %>%
  filter(sample == "drug" | drug == "DMSO") %>%
  distinct(conc_char, replicate,drug, IPR, freqCut_norm_mean, freqCut_norm)


eff.data.heatmap2 <- eff.data.heatmap %>%
  dplyr::select(-freqCut_norm_mean) %>%
  mutate(freqCut_norm = ave(freqCut_norm, conc_char, drug, replicate, IPR, FUN = mean)) %>%
  distinct() %>%
  mutate(freqCut_norm = log2(freqCut_norm)) %>%
  mutate(mod = Mod(freqCut_norm)) %>%
  mutate(max = ave(mod, drug, conc_char, replicate, FUN = max)) %>%
  dplyr::select(-mod) %>%
  spread(IPR, freqCut_norm) %>%
  mutate(conc_rep = paste(conc_char, replicate, sep = " ")) %>%
  group_by(conc_rep) %>%
  top_n(25, max) %>%
  ungroup() %>%
  dplyr::select(-max)

breaks <- seq(-0.2, 0.2, 0.004)

# eff.data.heatmap2 %<>% mutate(conc_rep = paste(conc_char, replicate, sep = " "))

for (i in unique(eff.data.heatmap2$conc_rep)) {
  pheatmap(as.matrix(eff.data.heatmap2[eff.data.heatmap2$conc_rep == i,] %>%
                       column_to_rownames('drug') %>%
                       dplyr::select(contains('IPR')) %>%
                       t()),
           border_color = "white",
           cellwidth = 12,
           cellheight = 12,
           breaks = breaks,
           cluster_rows = F,
           main = paste('efficiency change, concentration =', i),
           annotation_col = target,
           annotation_row = chromatin,
           color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdBu")))(100),
           annotation_colors = annotation_colors_scr, annotation_legend = T)
}
```

```{r distribution of the MMEJ score in the controls}
mmejscore_DMSO_matrix_list = screen_indel_split_tib %>%  
  filter(drug == "DMSO") %>%
  mutate(ID = gsub("^E.*_.*_([12]_...)$", "\\1\\2", ID)) %>% 
  distinct(ID, MMEJscore_split, replicate, tech, concentration, barcode) %>%
  pivot_wider(names_from = c("replicate", "tech", "concentration"), 
              values_from = "MMEJscore_split") %>%
  group_split(barcode, .keep = FALSE)

mmejscore_DMSO_matrix_list_new = lapply(mmejscore_DMSO_matrix_list, '[', -1)

# MMEJscoreDMSOvar = mmejscore_DMSO_matrix %>%
#   rownames_to_column(var = "ID") %>%
#   pivot_longer(cols = starts_with("E"), names_to = "rep") %>%
#   group_by(rep)

sep_conc = screen_indel_split_tib %>%  
  filter(drug == "DMSO") %>%
  mutate(ID = gsub("^E.*_(.*_.*)_[12]_...$", "\\1", exp),
         plates = paste(replicate, tech, concentration, sep = "_")) %>% 
  distinct(ID,plates, freqCut_split, MMEJscore_split, replicate, tech, concentration, barcode)

for (i in unique(sep_conc$barcode)) {
  btest = bartlett.test(MMEJscore_split ~ plates, data = filter(sep_conc, barcode == i))
  print(btest)
}

sep_conc %>% 
  filter(barcode == "ACCCCTAAAGGCGCTG") %>% 
  ggplot(., aes(plates, MMEJscore_split)) + geom_jitter()

sep_conc %>% 
  filter(barcode == "ACCCCTAAAGGCGCTG") %>% 
  ggplot(., aes(plates, freqCut_split)) + geom_jitter()

sep_conc %>%  
  ggplot(., aes(plates, freqCut_split, color = barcode)) + geom_jitter()

sep_conc %>%  
  ggplot(., aes(plates, MMEJscore_split, color = barcode)) + geom_jitter()

comb_conc = screen_indel_split_tib %>%  
  filter(drug == "DMSO") %>%
  mutate(ID = gsub("^E.*_(.*_.*)_[12]_...$", "\\1", exp),
         plates = paste(replicate, tech, sep = "_")) %>% 
  distinct(ID,plates, freqCut_split, MMEJscore_split, replicate, tech, barcode)

for (i in unique(comb_conc$barcode)) {
  btest = bartlett.test(MMEJscore_split ~ plates, data = filter(comb_conc, barcode == i))
  print(btest)
  }
  
comb_conc %>% 
  filter(barcode == "ACCCCTAAAGGCGCTG") %>% 
  ggplot(., aes(plates, MMEJscore_split)) + geom_jitter()

comb_conc %>%  
  ggplot(., aes(plates, freqCut_split, color = barcode)) + geom_jitter()

comb_conc %>%  
  ggplot(., aes(plates, MMEJscore_split, color = barcode)) + geom_jitter()

mmejscore_DMSO_tib = screen_indel_split_tib %>%  
  filter(drug == "DMSO") %>%
  mutate(ID = gsub("^E.*_(.*_.*)_[12]_...$", "\\1", exp)) %>%
  distinct(ID, MMEJscore_split, replicate, tech, concentration, drug, barcode)

mmejscore_DMSO_tib %>% 
  ggplot(., aes(ID, MMEJscore_split)) + 
  geom_jitter() + 
  facet_grid(barcode ~ replicate, scales = "free_y")
```


```{r}
# For MMEJ z-score
mmejzscore_matrix = screen_indel_split_tib %>%  
  filter(sample == "drug") %>%
  mutate(ID = paste(gsub("^E.*_(.*_[12]_...)$", "\\1\\2", ID), barcode, sep = "_")) %>% 
  distinct(ID, MMEJ_zscore_split, replicate, tech) %>%
  pivot_wider(., names_from = c("replicate", "tech"), values_from = "MMEJ_zscore_split") %>%
  column_to_rownames(., var = "ID")
# 
chart.Correlation(mmejzscore_matrix, histogram=TRUE, pch=19)

# For standard MMEJ score
mmejscore_matrix = screen_indel_split_tib %>%  
  filter(sample == "drug") %>%
  mutate(ID = paste(gsub("^E.*_(.*_[12]_...)$", "\\1\\2", ID), barcode, sep = "_")) %>% 
  distinct(ID, MMEJscore_split, replicate, tech) %>%
  pivot_wider(., names_from = c("replicate", "tech"), values_from = "MMEJscore_split") %>%
  column_to_rownames(., var = "ID")
# 
chart.Correlation(mmejscore_matrix, histogram=TRUE, pch=19)

MMEJscorevar = mmejscore_matrix %>%
  rownames_to_column(var = "ID") %>%
  pivot_longer(.,cols = starts_with("E"), names_to = "rep") %>%
  group_by(rep)

MMEJscorevar %>%
  summarise(
    count = n(),
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE))
  

screen.indel.dt %>% 
  filter(sample == "drug" & replicate == "E1504") %>% 
  distinct(barcode, tech, ID, freqCut_norm_split) %>% 
  mutate(bc_ID = paste(ID, barcode, sep = "_")) %>% select(-barcode, -ID) %>% 
  pivot_wider(., names_from = tech, values_from = freqCut_norm_split) %>%
  column_to_rownames(., var = "bc_ID") %>% 
  chart.Correlation(., histogram=TRUE, pch=19)

screen.indel.dt %>% 
  filter(sample == "drug" & replicate == "E177") %>% 
  distinct(barcode, tech, ID, freqCut_norm_split) %>% 
  mutate(bc_ID = paste(ID, barcode, sep = "_")) %>% select(-barcode, -ID) %>% 
  pivot_wider(., names_from = tech, values_from = freqCut_norm_split) %>%
  column_to_rownames(., var = "bc_ID") %>% 
  chart.Correlation(., histogram=TRUE, pch=19)

screen.indel.dt %>% 
  filter(sample == "drug" & replicate == "E177") %>% 
  distinct(barcode, tech, ID, freqCut) %>% 
  mutate(bc_ID = paste(ID, barcode, sep = "_")) %>% select(-barcode, -ID) %>% 
  pivot_wider(., names_from = tech, values_from = freqCut) %>%
  column_to_rownames(., var = "bc_ID") %>% 
  chart.Correlation(., histogram=TRUE, pch=19)


# Compute the analysis of variance
res.aov <- aov(value ~ rep, data = MMEJscorevar)
# Summary of the analysis
summary(res.aov)

# Compute the analysis of variance
res.aov <- aov(value ~ rep, data = filter(MMEJscorevar, grepl("E177", rep)))
# Summary of the analysis
summary(res.aov)

# Compute the analysis of variance
res.aov <- aov(value ~ rep, data = filter(MMEJscorevar, grepl("E1504", rep)))
# Summary of the analysis
summary(res.aov)

fligner.test(value ~ rep, data = MMEJscorevar)
fligner.test(value ~ rep, data = filter(MMEJscorevar, grepl("E177", rep)))
fligner.test(value ~ rep, data = filter(MMEJscorevar, !grepl("E177", rep))) 

```


```{r}
screen_indels_tib %>% 
  filter(drug == "Barasertib (AZD1152-HQPA)", conc_char == "1 µM", type %in% c("core", "grouped_indel")) %>% 
  ggplot(., aes(mutation, freq_split , color = color)) +
    geom_quasirandom() +
    theme_bw(base_size = 18) +
    ylim(0, 1) +
    theme(legend.position = c(0.1, 0.8)) +
    scale_y_continuous(name="frequency") +
    scale_x_discrete(name="indel size") + 
  facet_grid(tech ~ replicate)
```


## Plotting for B4 meeting
Data loaded from Figure 1 script

```{r}
cols = c("100 nM  < 0.05 p.val" = "gray40", 
         "100 nM N.S." =  "gray90",
         "1 µM  < 0.05 p.val" = "gray20", 
         "1 µM N.S." =   "gray80",
         "10 µM  < 0.05 p.val" = "black", 
         "10 µM N.S." = "gray70")

indel.data %>%
  filter(sample == "drug") %>%
  distinct(mean_eff_zscore_comb , IPR, drug, conc_char, sample) %>%
  mutate(signif = ifelse(Mod(mean_eff_zscore_comb) > 1.96, " < 0.05 p.val", "N.S."),
         signif_col = paste(conc_char, signif),
          IPR = factor(gsub("IPR", "", IPR), levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19")),
         conc_char = factor(conc_char, levels = c("100nM", "1 µM", "10 µM"))) %>%
  ggplot(.,
       aes(x = IPR, y = mean_eff_zscore_comb, 
           color = signif_col, 
           group = conc_char)) +
  geom_quasirandom(dodge.width = 0.75) +
  geom_hline(linetype = "dashed", yintercept = 1.96) +
  geom_hline(linetype = "dashed", yintercept = -1.96) +
  scale_color_manual(values = cols) +
  theme_bw(base_size = 16)
```

```{r}
indel.data %>%
  filter(sample == "drug") %>%
  distinct(MMEJ_zscore_comb , IPR, drug, conc_char, sample) %>%
  mutate(signif = ifelse(Mod(MMEJ_zscore_comb) > 1.96, " < 0.05 p.val", "N.S."),
         signif_col = factor(paste(conc_char, signif), 
                             levels = c("100 nM  < 0.05 p.val", 
                                        "1 µM  < 0.05 p.val", 
                                        "10 µM  < 0.05 p.val", 
                                        "100 nM N.S.",
                                        "1 µM N.S.",
                                        "10 µM N.S.")),
         IPR = factor(gsub("IPR", "", IPR), levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19")),
         conc_char = factor(conc_char, levels = c("100nM", "1 µM",  "10 µM"))) %>%
  arrange(conc_char) %>%
  ggplot(.,
         aes(x = IPR, y = MMEJ_zscore_comb, 
             color = signif_col, 
             group = conc_char)) +
  geom_quasirandom(dodge.width = 0.75) +
  geom_hline(linetype = "dashed", yintercept = 1.96) +
  geom_hline(linetype = "dashed", yintercept = -1.96) +
  scale_color_manual(values = cols) +
  theme_bw(base_size = 16)

signif_col
```


```{r}
# Generate heatmap: select top 15 drugs (highest change at any IPR) per concentration
eff.data.heatmap <- indel.data %>%
  #filter(target != "Aurora Kinase") %>%
  filter(sample == "drug" | drug %in% c("DMSO")) %>%
  #filter(Mod(eff_zscore_pooled_global_comb) >= 1.645) %>%  # we could also choose to display all drugs that have significant global hits
  distinct(conc_char,drug, IPR, MMEJ_zscore_comb  )

## Select drugs that have a large effect size in at least one location (some drugs might have a small global effect size, but large local)
eff.data.heatmap2 <- eff.data.heatmap %>%
  mutate(mod = Mod(MMEJ_zscore_comb  )) %>%
  mutate(max = ave(mod, drug, conc_char, FUN = max)) %>%
  filter(max > 2.58) %>% # p < 0.05
  dplyr::select(-mod, -max) %>%
  spread(IPR, MMEJ_zscore_comb)

breaks <- seq(-15, 15, 0.01)
scale_colors = colorRampPalette(rev(brewer.pal(n = 7, name = "RdBu")))(length(breaks))
scale_colors[between(breaks, -1.96, 1.96)] <- "gray80"

for (i in unique(eff.data.heatmap2$conc_char)) {
  pheatmap(as.matrix(eff.data.heatmap2[eff.data.heatmap2$conc_char == i,] %>%
                       column_to_rownames('drug') %>%
                       dplyr::select(contains('IPR')) %>%
                       t()),
           border_color = "white",
           cellwidth = 12,
           cellheight = 12,
           breaks = breaks,
           cluster_rows = F,
           main = paste('MMEJ ratio change, concentration =', i),
           annotation_col = target,
           annotation_row = chromatin,
           color = scale_colors,
           annotation_colors = annotation_colors_scr, annotation_legend = T)
}
```


```{r}
# Generate heatmap: select top 15 drugs (highest change at any IPR) per concentration
eff.data.heatmap <- indel.data %>%
  #filter(target != "Aurora Kinase") %>%
  filter(sample == "drug" | drug %in% c("DMSO", "DNA-PKi")) %>%
  #filter(Mod(eff_zscore_pooled_global_comb) >= 1.645) %>%  # we could also choose to display all drugs that have significant global hits
  distinct(conc_char,drug, IPR, mean_eff_zscore_comb )

## Select drugs that have a large effect size in at least one location (some drugs might have a small global effect size, but large local)
eff.data.heatmap2 <- eff.data.heatmap %>%
  mutate(mod = Mod(mean_eff_zscore_comb   )) %>%
  mutate(max = ave(mod, drug, conc_char, FUN = max)) %>%
  filter(max > 2.58) %>% # p < 0.05
  dplyr::select(-mod, -max) %>%
  spread(IPR, mean_eff_zscore_comb  )

breaks <- seq(-10, 10, 0.01)

for (i in unique(eff.data.heatmap2$conc_char)) {
  pheatmap(as.matrix(eff.data.heatmap2[eff.data.heatmap2$conc_char == i,] %>%
                       column_to_rownames('drug') %>%
                       dplyr::select(contains('IPR')) %>%
                       t()),
           border_color = "white",
           cellwidth = 12,
           cellheight = 12,
           breaks = breaks,
           cluster_rows = F,
           main = paste('Indel rate z-score, concentration =', i),
           annotation_col = target,
           annotation_row = chromatin,
           color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdBu")))(length(breaks)),
           annotation_colors = annotation_colors_scr, annotation_legend = T)
}
```

```{r check belinostat and CUDC}
mut.data %>% pull(drug) %>% unique() %>% .[grepl("Res", .)]

ratio.data = readRDS("/DATA/projects/DSBrepair/data/R/rs20220207_episcreen/rs20220207_episcreen_ratios.RDS") 

mut.data.filt = mut.data %>% 
  filter(drug %in% c("CUDC-101","Belinostat (PXD101)","DMSO") & conc_char == "100 nM" & type %in% c("core", "grouped_indel")) %>% 
  distinct(IPR, mutation, color, type, drug, freq_mean, freq_sd)

colores <- c("wt" = "#808184", "other" = "black", "NHEJ" = "#e1251b", "MMEJ" = "#26419a", "SSTR" = "#007A4C")


p <- ggplot(mut.data.filt, 
            aes(mutation, freq_mean)) + 
  geom_bar(stat = "identity", aes(fill = color)) + 
  scale_fill_manual("legend", values = colores) + 
  theme_bw() +
  scale_y_continuous(name="frequency") +
  scale_x_discrete(name="indel size", breaks = c("<-14", -7, 0, 1, ">2")) +
  geom_errorbar(aes(ymin=freq_mean-freq_sd, ymax=freq_mean+freq_sd), width=.2,
                position=position_dodge(.9)) 
p + facet_grid(IPR ~ drug)

check_tib = ratio.data %>% 
  filter(drug %in% c("CUDC-101","Belinostat (PXD101)","DMSO")  & conc_char == "100 nM") %>%
  distinct(MMEJ_zscore_comb, IPR, drug)

ggplot(check_tib, aes(drug, MMEJ_zscore_comb, color = IPR)) + geom_quasirandom() + theme_bw(base_size = 16)

check_tib %>% filter(drug != "DMSO") %>% pivot_wider(names_from = drug, values_from = MMEJ_zscore_comb) %>% ggplot(., aes(`Belinostat (PXD101)`, `CUDC-101`)) + 
  geom_point() + geom_smooth(method = "lm")

p1 = ratio.data %>% 
  filter(drug %in% c("CUDC-101","Belinostat (PXD101)")  & conc_char == "100 nM") %>%
  distinct(MMEJ_zscore_comb, IPR, drug) %>%
 pivot_wider(names_from = drug, values_from = MMEJ_zscore_comb) %>% ggplot(., aes(`CUDC-101`, `Belinostat (PXD101)`)) + 
  geom_point() + geom_smooth(method = "lm")

p2 = ratio.data %>% 
  filter(drug %in% c("Mocetinostat (MGCD0103)","Belinostat (PXD101)")  & conc_char == "100 nM") %>%
  distinct(MMEJ_zscore_comb, IPR, drug) %>%
 pivot_wider(names_from = drug, values_from = MMEJ_zscore_comb) %>% ggplot(., aes(`Mocetinostat (MGCD0103)`, `Belinostat (PXD101)`)) + 
  geom_point() + geom_smooth(method = "lm")

p3 = ratio.data %>% 
  filter(drug %in% c("Mocetinostat (MGCD0103)","EPZ-6438")  & conc_char == "100 nM") %>%
  distinct(MMEJ_zscore_comb, IPR, drug) %>%
 pivot_wider(names_from = drug, values_from = MMEJ_zscore_comb) %>% ggplot(., aes(`Mocetinostat (MGCD0103)`, `EPZ-6438`)) + 
  geom_point() + geom_smooth(method = "lm")

boundaries <- c(-5,-2.5, 2.5 , 5)
ratio.data %>% 
  filter(drug %in% c("Mocetinostat (MGCD0103)", "Resminostat", "Belinostat (PXD101)", "CUDC-101", "Vorinostat (SAHA, MK0683)", "DNA-PKi")  & conc_char == "100 nM") %>%
  distinct(MMEJ_zscore_comb, IPR, drug) %>%
  pivot_wider(names_from = drug, values_from = MMEJ_zscore_comb) %>% 
  select(-IPR) %>%
  ggpairs(.,
          upper = list(continuous = corColor),
          lower = list(continuous = function(data, mapping, ...) {
            ggally_points(data = data, mapping = mapping, alpha = 0.6, size = 0.5) +
              # scale_y_continuous(breaks = c(-2, -1, 0), limits = c(-1.9, 0.5)) +
              # scale_x_continuous(breaks = c(-2, -1, 0), limits = c(-1.9, 0.5)) +
              geom_abline(slope = 1, lty = "twodash", col = "grey") +
              geom_smooth(method = "lm", color = "red", lty = "dashed", size = 0.5)}),
          diag = list(continuous = function(data, mapping, ...) {
            ggally_densityDiag(data = data, mapping = mapping, alpha = 0.3, fill = "red")})) +
  xlab("MMEJ ratio change (log2)") +
  ylab("MMEJ ratio change (log2)")


cormat = ratio.data %>% 
  filter(target %in% c("HDAC")) %>%
  mutate(drug_conc = paste(drug, conc_char, sep = " ")) %>%
  distinct(MMEJ_zscore_comb, IPR, drug_conc) %>%
  pivot_wider(names_from = drug_conc, values_from = MMEJ_zscore_comb) %>% 
  select(-IPR) %>%
  cor()



reorder_cormat <- function(cormat){
# Use correlation between variables as distance
dd <- as.dist((1-cormat)/2)
hc <- hclust(dd)
cormat <-cormat[hc$order, hc$order]
}

# Get lower triangle of the correlation matrix
get_lower_tri<-function(cormat){
  cormat[upper.tri(cormat)] <- NA
  return(cormat)
}
# Get upper triangle of the correlation matrix
get_upper_tri <- function(cormat){
  cormat[lower.tri(cormat)]<- NA
  return(cormat)
}

# Reorder the correlation matrix
cormat <- reorder_cormat(cormat)
upper_tri <- get_upper_tri(cormat)
# Melt the correlation matrix
melted_cormat <- melt(upper_tri, na.rm = TRUE)
# Create a ggheatmap
ggheatmap <- ggplot(melted_cormat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
    name="Pearson\nCorrelation") +
  theme_minimal()+ # minimal theme
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()
# Print the heatmap
print(ggheatmap)

```
```{r}
cormat = ratio.data %>% 
  filter(target %in% c("Aurora Kinase")) %>%
  mutate(drug_conc = paste(drug, conc_char, sep = " ")) %>%
  distinct(MMEJ_zscore_comb, IPR, drug_conc) %>%
  pivot_wider(names_from = drug_conc, values_from = MMEJ_zscore_comb) %>% 
  select(-IPR) %>%
  cor()



reorder_cormat <- function(cormat){
# Use correlation between variables as distance
dd <- as.dist((1-cormat)/2)
hc <- hclust(dd)
cormat <-cormat[hc$order, hc$order]
}

# Get lower triangle of the correlation matrix
get_lower_tri<-function(cormat){
  cormat[upper.tri(cormat)] <- NA
  return(cormat)
}
# Get upper triangle of the correlation matrix
get_upper_tri <- function(cormat){
  cormat[lower.tri(cormat)]<- NA
  return(cormat)
}

# Reorder the correlation matrix
cormat <- reorder_cormat(cormat)
upper_tri <- get_upper_tri(cormat)
# Melt the correlation matrix
melted_cormat <- melt(upper_tri, na.rm = TRUE)
# Create a ggheatmap
ggheatmap <- ggplot(melted_cormat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
    name="Pearson\nCorrelation") +
  theme_minimal()+ # minimal theme
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()
# Print the heatmap
print(ggheatmap)
```


```{r}

```

```{r}
mut.data = readRDS("/DATA/projects/DSBrepair/data/R/rs20220207_episcreen/rs20220207_episcreen_mutations.RDS") 

mut.data.filt = mut.data %>% 
  filter(drug %in% c("PCI-24781 (Abexinostat)","DMSO") & conc_char == "100 nM" & type %in% c("core", "grouped_indel")) %>% 
  distinct(IPR, mutation, color, type, drug, freq_mean, freq_sd)

colores <- c("wt" = "#808184", "other" = "black", "NHEJ" = "#e1251b", "MMEJ" = "#26419a", "SSTR" = "#007A4C")


p <- ggplot(mut.data.filt, 
            aes(mutation, freq_mean)) + 
  geom_bar(stat = "identity", aes(fill = color)) + 
  scale_fill_manual("legend", values = colores) + 
  theme_bw() +
  scale_y_continuous(name="frequency") +
  scale_x_discrete(name="indel size", breaks = c("<-14", -7, 0, 1, ">2")) +
  geom_errorbar(aes(ymin=freq_mean-freq_sd, ymax=freq_mean+freq_sd), width=.2,
                position=position_dodge(.9)) 
p + facet_grid(IPR ~ drug)


mut.data.filt = mut.data %>% 
  filter(drug %in% c("PCI-24781 (Abexinostat)","DMSO") & conc_char == "100 nM" & mutation == 0) %>% 
  distinct(IPR, color, type, drug, freq_mean, freq_sd)

IPR_levels = mut.data.filt %>% filter(drug == "DMSO") %>% distinct(IPR, freq_mean) %>% arrange(-freq_mean) %>% pull(IPR) %>% as.character()

mut.data.filt %<>% mutate(IPR = factor(IPR, levels = IPR_levels))

ggplot(mut.data.filt, 
            aes(IPR, freq_mean, fill = drug)) + 
  geom_bar(stat = "identity", position = position_dodge(1)) + 
  theme_bw() +
  scale_y_continuous(name="frequency") +
  geom_errorbar(aes(ymin=freq_mean-freq_sd, ymax=freq_mean+freq_sd), width=.2,
                position = position_dodge(width = 1))

mut.data.filt = mut.data %>% 
  filter(drug %in% c("Vorinostat (SAHA, MK0683)", "PCI-24781 (Abexinostat)","DMSO") & conc_char == "100 nM" & type %in% c("core", "grouped_indel"), IPR %in% c("IPR16", "IPR10")) %>% 
  distinct(IPR, mutation, color, type, drug, freq_mean_rep, freq_sd_rep, replicate)

colores <- c("wt" = "#808184", "other" = "black", "NHEJ" = "#e1251b", "MMEJ" = "#26419a", "SSTR" = "#007A4C")


p <- ggplot(mut.data.filt, 
            aes(mutation, freq_mean_rep)) + 
  geom_bar(stat = "identity", aes(fill = color)) + 
  scale_fill_manual("legend", values = colores) + 
  theme_bw() +
  scale_y_continuous(name="frequency") +
  scale_x_discrete(name="indel size", breaks = c("<-14", -7, 0, 1, ">2")) +
  geom_errorbar(aes(ymin=freq_mean_rep-freq_sd_rep, ymax=freq_mean_rep+freq_sd_rep), width=.2,
                position=position_dodge(.9)) 
p + facet_grid(IPR + replicate ~ drug)

mut.data %>% pull(drug) %>% unique() %>% .[grepl("Bara", .)]


mut.data.filt = mut.data %>% 
  filter(drug %in% c("Barasertib (AZD1152-HQPA)", "2-Methoxyestradiol (2-MeOE2)","DMSO") & conc_char == "100 nM" & type %in% c("core", "grouped_indel"), IPR %in% c("IPR16")) %>% 
  distinct(IPR, mutation, color, type, drug, freq_mean_rep, freq_sd_rep, replicate)

colores <- c("wt" = "#808184", "other" = "black", "NHEJ" = "#e1251b", "MMEJ" = "#26419a", "SSTR" = "#007A4C")


p <- ggplot(mut.data.filt, 
            aes(mutation, freq_mean_rep)) + 
  geom_bar(stat = "identity", aes(fill = color)) + 
  scale_fill_manual("legend", values = colores) + 
  theme_bw() +
  scale_y_continuous(name="frequency") +
  scale_x_discrete(name="indel size", breaks = c("<-14", -7, 0, 1, ">2")) +
  geom_errorbar(aes(ymin=freq_mean_rep-freq_sd_rep, ymax=freq_mean_rep+freq_sd_rep), width=.2,
                position=position_dodge(.9)) 
p + facet_grid(IPR + replicate ~ drug)

```


```{r}
validation_indels_tib %>% filter(replicate == "mean" & plasmid == "LBR2") %>% distinct(barcode, drug, NHEJ_MMEJ) %>% pivot_wider(names_from = drug, values_from = NHEJ_MMEJ) %>%
  mutate(log2dist_mmej = log2(Vorinostat)/log2(DMSO)) %>% ggplot(.) + geom_density(aes(log2dist_mmej))

validation_indels_tib %>% filter(replicate == "mean" & plasmid == "LBR2") %>% distinct(barcode, drug, MMEJ_NHEJ) %>% pivot_wider(names_from = drug, values_from = MMEJ_NHEJ) %>%
  mutate(log2dist_mmej = log2(Vorinostat)/log2(DMSO)) %>% ggplot(.) + geom_density(aes(log2dist_mmej))

```


```{r}
indel.data  %>% 
  select(barcode, drug, conc_char, target,mean_eff_zscore_comb, all_of(chromatin.features)) %>% 
  filter(grepl("Mocet", drug), conc_char == "100 nM") %>% 
  pivot_longer(cols = all_of(chromatin.features), names_to = "feature", values_to = "zscore") %>%
  ggplot(., aes(zscore  
                ,mean_eff_zscore_comb)) + 
  geom_point(mapping =  aes(color = abs(mean_eff_zscore_comb) > 1.96)) +
  stat_cor(method = "spearman") + 
  geom_smooth(method = "lm") + 
  theme_bw() +
  facet_wrap(. ~ feature)
```



### Data import

```{r data import, echo = FALSE, warning = FALSE}
# Import data from preprocessing script
indel.data <- readRDS("/DATA/usr/m.trauernicht/projects/EpiScreen/files_scripts/mt20220105_episcreen.RDS")

# Complete data without exlcluding wells <0.45 viability (I need this for plotting)
viability.data = as.data.table(readRDS("/DATA/projects/DSBrepair/git/EpiScreen/files_scripts/rs20211221_Episcreen_Reads_Viab_Metadata.RDS")) %>%
  dplyr::select(ID, drug, target, replicate, viability, conc_char, tech)
```



## DMSO indel scores

```{r, warning = FALSE}


# Correlation DMSO MMEJ scores
indel.data$ID_2 <-  gsub("^E[0-9]{3,4}_", "", indel.data$ID)
indel.data.DMSO.rep <- indel.data %>% 
  filter(drug == "DMSO") %>%
  dplyr::select(MMEJscore, ID_2, IPR, tech, replicate, chromatin) %>%
  unique() %>%
  spread(replicate, MMEJscore)

sp <- ggscatter(indel.data.DMSO.rep, x = "E177", y = "E1504", color = "chromatin",
                size = 1.5, add = "reg.line",
   add.params = list(color = "black", fill = "lightgray"),
   conf.int = TRUE, ylab = "rep 2", xlab = "rep 1")

sp + stat_cor(method = "pearson", label.x = 0.1, label.y = 0.4)
  scale_color_manual(values = c(colors_diverse, "grey"))

# Correlation DMSO cutting efficiency
indel.data.DMSO.rep <- indel.data %>% 
  filter(drug == "DMSO") %>%
  dplyr::select(freqCut, ID_2, IPR, replicate, chromatin) %>%
  unique() %>%
  spread(replicate, freqCut)

sp <- ggscatter(indel.data.DMSO.rep, x = "E177", y = "E1504", color = "chromatin",
                size = 2, add = "reg.line",
   add.params = list(color = "black", fill = "lightgray"), 
   conf.int = TRUE, ylab = "rep 2", xlab = "rep 1")

sp + stat_cor(method = "pearson", label.x = 0.6, label.y = 0.9) + 
  theme_pubr(border = T) + 
  scale_color_manual(values = c(colors_diverse, "grey"))
```




## Drug effects per target group

```{r Quality check data, warning = FALSE}
# Beeswarm plot of MMEJ score of all drugs, highlighting controls
ggplot_custom(data = indel.data %>%
         dplyr::select(MMEJ_zscore, sample, drug, conc_char, IPR, replicate) %>%
         unique(), 
       aes(y = MMEJ_zscore, x = 'x', color = sample)) + 
  geom_quasirandom(dodge.width = 0.75) +
  geom_boxplot(position = position_dodge(0.75), alpha = 0.4) +
  xlab("") + ylab("MMEJ z-score") +
  scale_color_manual(values = colors_diverse) +
  facet_grid(replicate~conc_char)

ggplot_custom(data = indel.data %>%
                filter(sample != "DNA-PKi (NHEJ control)", sample != "Mirin (MMEJ control)", sample != "DMSO (neg control)") %>%
                  dplyr::select(MMEJ_zscore_drug_comb, sample, drug, conc_char) %>%
                  unique(), 
              aes(y = MMEJ_zscore_drug_comb, x = conc_char)) + 
    geom_quasirandom(dodge.width = 0.75) +
    geom_boxplot(position = position_dodge(0.75), alpha = 0.4) +
    xlab("") + ylab("MMEJ z-score") 

ggplot_custom(data = indel.data %>%
                filter(sample != "DNA-PKi (NHEJ control)", sample != "Mirin (MMEJ control)", sample != "DMSO (neg control)") %>%
                  dplyr::select(freqCut_norm_mean_drug, sample, drug, conc_char) %>%
                  unique(), 
              aes(y = log2(freqCut_norm_mean_drug) , x = conc_char)) + 
    geom_quasirandom(dodge.width = 0.75) +
    geom_boxplot(position = position_dodge(0.75), alpha = 0.4) +
    xlab("") + ylab("log2(cutting efficiency)") 


      

# Integral of MMEJ-zscore density plot per target group
ggplot_custom(data = indel.data, 
       aes(x = MMEJ_zscore)) +
  xlab("logratio") + ylab("acumulative value")+ stat_ecdf(aes(colour = target))+ 
  labs(title = "accumulative logratio of all targets") + facet_wrap(~replicate)

# Integral of freqCut density plot
ggplot_custom(data = indel.data, 
       aes(x = freqCut_mean)) +
  xlab("efficiency: normalized over plate") + stat_ecdf(aes(colour = target))+ 
  labs(title = "integral of efficiency density")

# Total amount of drugs per target group
ggplot_custom(indel.data, aes(x = reorder(target,target, function(x)-length(x)))) +
  geom_bar()+theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 12))+ 
  ylab("datapoints") + xlab("target group")+ labs(title = "datapoints per target group")


indel.data2 <- indel.data
indel.data2$zscore_change <- "<1"
indel.data2$zscore_change[abs(indel.data2$MMEJ_zscore)>1] <- "1-2"
indel.data2$zscore_change[abs(indel.data2$MMEJ_zscore)>2] <- ">2"
indel.data2$zscore_change <- factor(indel.data2$zscore_change, levels = c( ">2", "1-2", "<1"))
indel.data2 <- indel.data2 %>%
  mutate(size = ave(target, target, conc_char, replicate, zscore_change, FUN = function(x) length(x)),
         total_size = ave(target, target, conc_char, replicate, FUN = function(x) length(x)))


ggplot_custom(indel.data2 %>%
         dplyr::select(target, size, zscore_change, conc_char, total_size, replicate) %>%
         unique(), aes(x = reorder(target, as.numeric(total_size)), 
                   y = as.numeric(size), 
                       fill = zscore_change)) + 
      geom_bar(stat="identity") +
    labs(fill = "z-score")+
  scale_fill_manual(values = colors_diverse[rev(seq(1, length(colors_diverse), 2))])+
  coord_flip()+ 
  ylab("Amount of drugs per Category") + theme(axis.title.y = element_blank())+
  theme(text = element_text(size = 14), axis.text.y = element_text(size = 12))+
  facet_grid(replicate~conc_char)
```



## Correlation plots

```{r correlation plots, warning = FALSE}
# Technical replicate correlation MMEJ z-score
indel.data2 <- indel.data.split %>%
  filter(sample == "drug", drug != "Mirin", drug != "DNA-PKi", conc_char == '1 µM') %>%
  mutate(rep = paste(replicate, tech, sep = "_")) %>%
  dplyr::select(rep, drug, MMEJ_zscore_split_drug) %>%
  unique() %>%
  spread(rep, MMEJ_zscore_split_drug) %>%
  column_to_rownames("drug")

indel.data2.cor <- cor(indel.data2, method = "spearman")

mybreaks <- seq(0.6,1,0.004)
pheatmap(indel.data2.cor, 
         breaks = mybreaks, 
         cluster_rows = F,
         cluster_cols = F,
         border_color = "black",
         color = colorRampPalette(brewer.pal(n = 7, name = "Greys"))(100))

ggplot_custom(indel.data2, aes(x = E1504_1, y = E177_1)) +
  geom_point() +
  geom_smooth(method = "lm", color = colors_diverse[1]) 



# Plot the mean MMEJ zscore vs the SD - maybe we can identify a cutoff in that plot to remove drugs that have different effects in the two replicates (this is more informative than just correlating the two replicates)
indel.data2 <- indel.data %>% 
  filter(drug != "DNA-PKi") %>%
  dplyr::select(drug, conc_char, replicate, ID_2, MMEJscore_drug) %>%
  unique() %>%
  mutate(MMEJ_zscore_drug_sd = ave(MMEJscore_drug, ID_2, FUN = function(x) sd(x)),
         MMEJ_zscore_drug_sd = sqrt(MMEJ_zscore_drug_sd),
         mean_MMEJ = ave(MMEJscore_drug, ID_2, FUN = function(x) mean(x)))

ggplot_custom(indel.data2, aes(x = abs(mean_MMEJ), y = MMEJ_zscore_drug_sd)) +
  xlab("MMEJ score - mean per drug") +
  ylab("sqrt of SD of the two replicates") +
  geom_smooth() +
  geom_point() +
  geom_abline(intercept = 0.3, slope = 0.15, linetype = "dashed")

# The same but for the raw -7 counts
indel.data2 <- indel.data %>% 
  filter(drug != "DNA-PKi") %>%
  dplyr::select(drug, conc_char, replicate, ID_2, freqMMEJ) %>%
  unique() %>%
  mutate(freqMMEJ = ave(freqMMEJ, ID_2, replicate, FUN = function(x) mean(x))) %>%
  mutate(MMEJ_count_sd = ave(freqMMEJ, ID_2, FUN = function(x) sd(x)),
         MMEJ_count_sd = sqrt(MMEJ_count_sd),
         mean_MMEJ = ave(freqMMEJ, ID_2, FUN = function(x) mean(x))) %>%
  unique()

ggplot_custom(indel.data2, aes(x = abs(mean_MMEJ), y = MMEJ_count_sd)) +
  xlab("MMEJ z-score - mean per drug") +
  ylab("sqrt of SD of the two replicates") +
  geom_smooth() +
  geom_point() 
 # geom_hline(yintercept = 0.5, linetype = "dashed") 


# Plot viability against read counts (for already filtered data)
indel.data2 <- indel.data %>%
  dplyr::select(viab_norm, ID, sum_pooled_bc_reads) %>%
  unique()







# Visualize logratio change and efficiency change in one plot to spot outliers
indel.data2 <- indel.data %>% 
  dplyr::select(drug, conc_char, replicate, MMEJ_zscore_mean_drug, freqCut_norm_mean_drug) %>%
  filter(drug != "DNA-PKi") %>%
  unique()

ggplot_custom(indel.data2, aes(x = MMEJ_zscore_mean_drug, y = log2(freqCut_norm_mean_drug), color = MMEJ_zscore_mean_drug)) +
  geom_point()+
  scale_color_gradient() +
  xlab("MMEJ z-score") + ylab("Efficiency relative to DMSO (log2)") +
  #gghighlight(abs(mean.MMEJ_zscore.drug) > 5, label_key = drug) 
  theme(text = element_text(size = 14)) +
  facet_wrap(~conc_char)


# Correlation plot mean viability vs. mean efficiency
indel.data2 <- indel.data %>% 
  dplyr::select(drug, conc_char, replicate, viab_norm, freqCut_norm_mean_drug) %>% 
  unique() %>%
  mutate(viability_drug = ave(viab_norm, drug, conc_char, FUN = function(x) mean(x))) %>%
  dplyr::select(-viab_norm) %>%
  unique()

ggplot_custom(indel.data2, aes(x = viability_drug, y = log2(freqCut_norm_mean_drug))) +
  geom_point() +
  xlab("Viability") + ylab("Cutting Efficiency Change") +
  #gghighlight(abs(mean.efficiency_zscore.drug) > 0.1, label_key = drug) + 
  facet_wrap(~conc_char) +
  geom_smooth(method = "lm", color = "black")


# Correlation plot mean viability vs. mean ratio
indel.data2 <- indel.data %>% 
  dplyr::select(drug, concentration, MMEJ_zscore_mean_bio_drug, mean.viability.drug, replicate) %>% 
  filter(drug != "DNA-PKi") %>% 
  unique()

ggplot_custom(indel.data2, aes(x = MMEJ_zscore_mean_bio_drug, y = mean.viability.drug)) +
  geom_point(color = ifelse(abs(indel.data2$MMEJ_zscore_mean_bio_drug) > 1, "black", "grey")) +
  xlab("MMEJ z-score") + ylab("Viability") +
  #gghighlight(abs(mean.MMEJ_zscore.drug) > 1.5, label_key = drug) + 
  
  theme(text = element_text(size = 14)) +
  facet_wrap(~concentration, nrow = 1, ncol = 3)


ggplot_custom(indel.data2[indel.data2$drug != "DNA-PKi",], aes(x = MMEJ_zscore_mean_bio_drug, y = mean.viability.drug)) +
  geom_point()+
  xlab("MMEJ z-score") + ylab("Viability")+
  geom_smooth(method = lm, color = "grey") +
  theme(text = element_text(size = 14))+
  facet_wrap(~concentration, nrow = 1, ncol = 3)
  
# Do we need a more stringent viability cutoff? 0.7?




# Correlation plots of the replicates
indel.data2 <- indel.data[-grep("DNA-PK|DMSO", indel.data$drug),]
indel.data.rep1 <- indel.data2 %>%
  filter(tech == '1') %>%
  dplyr::select(IPR, replicate, drug, concentration, 'R1' = MMEJscore)
indel.data.rep2 <- indel.data2 %>%
  filter(tech == '2') %>%
  dplyr::select(IPR, replicate, drug, concentration, 'R2' = MMEJscore)
indel.data.rep3 <- indel.data2 %>%
  filter(tech == '3') %>%
  dplyr::select(IPR, replicate, drug, concentration, 'R3' = MMEJscore)

indel.data.rep <- merge(indel.data.rep1, indel.data.rep2, all = T)
indel.data.rep <- merge(indel.data.rep, indel.data.rep3, all = T)

# Correlation matrix plot
correlation.plot.rep1 <- indel.data.rep %>% 
  filter(replicate == "E177") %>%
  dplyr::select(R1, R2, R3) %>% 
  na.omit()

correlation.plot.rep2 <- indel.data.rep %>% 
  filter(replicate == "E1504") %>%
  dplyr::select(R1, R2, R3) %>% 
  na.omit()

n <- sample(1:nrow(indel.data), 5000)
boundaries <- seq(from = 0.7, by = 0.05, length.out = 4)
plt_replicate1 <- ggpairs(correlation.plot.rep1,
               upper = list(continuous = corColor),
               lower = list(continuous = function(data, mapping, ...) {
                   ggally_points(data = data[n, ], mapping = mapping, alpha = 0.1, size = 0.5) +
                   geom_abline(slope = 1, lty = "dashed", col = "red")
                   }),
               diag = list(continuous = function(data, mapping, ...) {
                   ggally_densityDiag(data = data, mapping = mapping, alpha = 0.3, fill = "red")
                   })) +
  ggtitle("Correlation Between Technical Replicates - replicate 1") +
  theme(text = element_text(size = 20))+
  xlab("MMEJ score") +
  ylab("MMEJ score") 
  # 

plt_replicate2 <- ggpairs(correlation.plot.rep2,
               upper = list(continuous = corColor),
               lower = list(continuous = function(data, mapping, ...) {
                   ggally_points(data = data[n, ], mapping = mapping, alpha = 0.1, size = 0.5) +
                   geom_abline(slope = 1, lty = "dashed", col = "red")
                   }),
               diag = list(continuous = function(data, mapping, ...) {
                   ggally_densityDiag(data = data, mapping = mapping, alpha = 0.3, fill = "red")
                   })) +
  ggtitle("Correlation Between Technical Replicates - replicate 2") +
  theme(text = element_text(size = 20))+
  xlab("MMEJ score") +
  ylab("MMEJ score") 
  # 

print(plt_replicate1)
print(plt_replicate2)



# Correlation between biological replicates
indel.data2 <- indel.data[-grep("DNA-PK|DMSO", indel.data$drug),] %>%
  dplyr::select(MMEJ_zscore_mean_bio_drug, replicate, drug, concentration) %>%
  unique() %>%
  spread(key = replicate, value = MMEJ_zscore_mean_bio_drug)

sp <- ggscatter(indel.data2, x = "E177", y = "E1504",
                size = 1.5, add = "reg.line",
   add.params = list(color = "blue", fill = "lightgray"), title = "mean drug effects on MMEJ-zscore rep 1 vs. rep 2",
   conf.int = TRUE, ylab = "rep 2", xlab = "rep 1")

sp + stat_cor(method = "pearson", label.x = -2, label.y = 1) + 
  facet_wrap(~concentration)


# Correlation between biological replicates - only DMSO - all IPRs
indel.data2 <- indel.data[grep("DMSO", indel.data$drug),] %>%
  dplyr::select(freqCut, replicate, drug, concentration, IPR, tech, drug_plate, well) %>%
  unique() %>%
  spread(key = replicate, value = freqCut)

sp <- ggscatter(indel.data2, x = "E177", y = "E1504",
                size = 1.5, add = "reg.line",
   add.params = list(color = "blue", fill = "lightgray"), title = "mean drug effects on efficiency rep 1 vs. rep 2",
   conf.int = TRUE, ylab = "rep 2", xlab = "rep 1")

sp + stat_cor(method = "pearson", label.x = 0.8, label.y = 0.7)
```



## Locally vs. globally acting drugs

```{r, warning = FALSE}
# Plotting efficiency per drug per IPR
ggplot_custom(indel.data %>%
         filter(drug != "DNA-PKi", target != "Negative Control", target != "MRN") %>%
         mutate(freqCut_mean = ave(freqCut, IPR, drug, concentration, FUN = function(x) mean(x))) %>% 
         dplyr::select(freqCut_mean, IPR, drug, concentration) %>% unique(), aes(x = IPR, y = freqCut_mean)) +
  geom_quasirandom() +
  
  facet_wrap(~concentration) +
  coord_flip()

# Plotting MMEJscore per drug per IPR
ggplot_custom(indel.data %>%
         filter(drug != "DNA-PKi", target != "Negative Control", target != "MRN") %>%
         dplyr::select(MMEJ_zscore_mean, IPR, drug) %>% unique(), aes(x = IPR, y = MMEJ_zscore_mean)) +
  geom_quasirandom() +
  
  coord_flip()




# Plotting the MMEJ z-score against the SD in the MMEJ z-score between the 18 IPRs
ggplot_custom(indel.data %>%
         filter(drug != "DNA-PKi", target != "Negative Control", target != "MRN") %>%
         mutate(MMEJ_zscore_sd_drug = ave(MMEJ_zscore_mean, drug, concentration, FUN = function(x) sd(x))) %>%
         dplyr::select(MMEJ_zscore_mean_drug, MMEJ_zscore_sd_drug, drug, concentration) %>%
         unique(),
       aes(x = MMEJ_zscore_mean_drug, y = MMEJ_zscore_sd_drug, 
           color = ifelse(abs(MMEJ_zscore_mean_drug) >= 0.5 & MMEJ_zscore_sd_drug > 1, colors_diverse[3], colors_diverse[1]))) +
  geom_point() +
  geom_hline(yintercept = 1, linetype = "dashed", alpha = 0.3) +
  geom_vline(xintercept = 0.5, linetype = "dashed", alpha = 0.3) +
  geom_vline(xintercept = -0.5, linetype = "dashed", alpha = 0.3) +
  xlab("MMEJ z-score per drug") +
  ylab("MMEJ z-score sd of IPRs") +
  facet_wrap(~concentration) +
  scale_color_identity()


ggplot_custom(indel.data %>%
         filter(drug != "DNA-PKi", target != "Negative Control", target != "MRN") %>%
         mutate(MMEJ_zscore_sd_drug = ave(MMEJ_zscore_mean, drug, concentration, FUN = function(x) sd(x))) %>%
         dplyr::select(MMEJ_zscore_mean_drug, MMEJ_zscore_sd_drug, drug, concentration, target) %>%
         unique(),
       aes(x = MMEJ_zscore_mean_drug, y = MMEJ_zscore_sd_drug, 
           color = ifelse(abs(MMEJ_zscore_mean_drug) >= 0.5 & MMEJ_zscore_sd_drug > 1, colors_diverse[1], colors_diverse[2]))) +
  geom_point() +
  geom_hline(yintercept = 1, linetype = "dashed", alpha = 0.3) +
  geom_vline(xintercept = 0.5, linetype = "dashed", alpha = 0.3) +
  geom_vline(xintercept = -0.5, linetype = "dashed", alpha = 0.3) +
    xlab("mean MMEJ z-score") +
    ylab("SD between IPRs") +
    facet_grid(concentration~target) +
    scale_color_identity()

indel.data$local <- "No"
indel.data$MMEJ_zscore_sd_drug <- ave(indel.data$MMEJ_zscore_mean, indel.data$drug, indel.data$concentration, FUN = function(x) sd(x))
indel.data$local[abs(indel.data$MMEJ_zscore_mean_drug) >= 0.5 & indel.data$MMEJ_zscore_sd_drug > 1] <- "Yes"




indel.data2 <- indel.data %>% 
  dplyr::select(drug, concentration, target, local) %>%
  unique()
indel.data2 <- indel.data2 %>%
  mutate(size = ave(target, target, concentration, local, FUN = function(x) length(x)),
         total_size = ave(target, target, concentration, FUN = function(x) length(x)))


ggplot_custom(indel.data2 %>%
         filter(concentration == "1") %>%
         dplyr::select(target, size, local, concentration, total_size) %>%
         unique(), aes(x = reorder(target, as.numeric(total_size)), 
                   y = as.numeric(size), 
                       fill = local)) + 
      geom_bar(stat="identity") +
    labs(fill = "locally acting drugs")+
  scale_fill_manual(values = colors_diverse[seq(1, length(colors_diverse), 2)])+
  coord_flip()+ 
  ylab("Amount of drugs per Category") + theme(axis.title.y = element_blank())+
  theme(text = element_text(size = 14), axis.text.y = element_text(size = 12))




ggplot_custom(indel.data %>%
         filter(drug != "DNA-PKi", target != "Negative Control", target != "MRN") %>%
         mutate(freqCut_norm_sd_drug = ave(freqCut_norm_mean, drug, concentration, FUN = function(x) sd(x))) %>%
         dplyr::select(freqCut_norm_sd_drug, freqCut_norm_mean_drug, drug, concentration) %>%
         unique(),
       aes(x = freqCut_norm_mean_drug, y = freqCut_norm_sd_drug, 
           color = ifelse(freqCut_norm_sd_drug > 0.02, colors_diverse[3], colors_diverse[1]))) +
  geom_point() +
  geom_hline(yintercept = 0.02, linetype = "dashed", alpha = 0.3) +
  geom_vline(xintercept = 1, linetype = "dashed", alpha = 0.3) +
  
  xlab("efficiency per drug") +
  ylab("efficiency sd of IPRs") +
  facet_grid(~concentration) +
  scale_color_identity()

indel.data2 <- indel.data
indel.data2$drug_category <- "drug"
indel.data2$drug_category[indel.data2$target == "HDAC"] <- "HDAC"
indel.data2$drug_category[indel.data2$drug == "DMSO"] <- "DMSO"

ggplot_custom(indel.data2 %>%
           filter(drug != "DNA-PKi", target != "Negative Control", target != "MRN") %>%
           mutate(freqCut_norm_sd_drug = ave(freqCut_norm_mean, drug, concentration, FUN = function(x) sd(x))) %>%
           dplyr::select(freqCut_norm_sd_drug, freqCut_norm_mean_drug, drug, concentration, replicate, drug_category) %>%
           unique(),
       aes(x = freqCut_norm_mean_drug, y = freqCut_norm_sd_drug, 
           color = ifelse(freqCut_norm_sd_drug > 0.02, "red", "black"))) +
    geom_quasirandom() +
    geom_hline(yintercept = 0.02, linetype = "dashed", alpha = 0.3) +
  geom_vline(xintercept = 1, linetype = "dashed", alpha = 0.3) +
    
    xlab("efficiency per drug") +
    ylab("efficiency sd of IPRs") +
    facet_wrap(~drug_category) +
    scale_color_identity()

ggplot_custom(indel.data2 %>%
           filter(drug != "DNA-PKi", target != "Negative Control", target != "MRN") %>%
           mutate(freqCut_norm_sd_drug = ave(freqCut_norm_mean, drug, concentration, FUN = function(x) sd(x))) %>%
           dplyr::select(freqCut_norm_sd_drug, freqCut_norm_mean_drug, drug, concentration, replicate, drug_category) %>%
           unique(),
       aes(x = drug_category, y = freqCut_norm_mean_drug)) +
    geom_quasirandom() +
  geom_boxplot(alpha = 0.7) +
    
    xlab("") +
    ylab("mean cutting efficiency") +
  facet_wrap(~concentration) +
    scale_color_identity()

ggplot_custom(indel.data2 %>%
           filter(drug != "DNA-PKi", target != "Negative Control", target != "MRN") %>%
           mutate(freqCut_norm_sd_drug = ave(freqCut_norm_mean, drug, concentration, FUN = function(x) sd(x))) %>%
           dplyr::select(freqCut_norm_sd_drug, freqCut_norm_mean_drug, drug, concentration, replicate, drug_category) %>%
           unique(),
       aes(x = drug_category, y = freqCut_norm_sd_drug)) +
    geom_quasirandom() +
  geom_boxplot(alpha = 0.7) +
    
    xlab("") +
    ylab("mean cutting efficiency") +
  facet_wrap(~concentration) +
    scale_color_identity()

```



## Spotting outliers
```{r, warning = FALSE}
# # Spot individual drug outliers per concentration
# indel.data2 <- indel.data
# indel.data2$MMEJ_zscore <- ave(indel.data2$MMEJ_zscore, indel.data2$concentration, indel.data2$drug, FUN = function(x) mean(x))
# indel.data2 <- indel.data2 %>% dplyr::select(drug, concentration, MMEJ_zscore)
# indel.data2 <- indel.data2[!duplicated(indel.data2),]
# indel.data2$concentration <- factor(indel.data2$concentration, levels=c("100nm", "1um", "10um"))
# 
# ggplot_custom(indel.data2 %>%
#          filter(drug != "DNA-PKi"), aes(x=concentration, y=MMEJ_zscore)) +
#   geom_quasirandom() + 
#   gghighlight(abs(MMEJ_zscore) > 6, label_key = drug) + 
#   
# # The same but only the range between 1 & 2
# ggplot_custom(indel.data2[abs(indel.data2$MMEJ_zscore) < 2,], aes(x=concentration, y=MMEJ_zscore)) +
#   geom_quasirandom() + 
#   gghighlight(abs(MMEJ_zscore) > 1.7, label_key = drug) + 
# 
# # Spot outliers by plotting DMSO versus drugs
# indel.data2 <- indel.data
# indel.data2$mean.ratio.bc.drug.conc <- ave(indel.data2$efficiency, 
#                                            indel.data2$concentration, indel.data2$drug, 
#                                            indel.data2$IPR, FUN = function(x) mean(x))
# indel.data2 <- indel.data2 %>% dplyr::select(IPR, drug, concentration, mean.ratio.bc.drug.conc)
# indel.data2 <- indel.data2[!duplicated(indel.data2),]
# indel.data2.high <- indel.data2[grep("1um", indel.data2$concentration),]
# indel.data2.high <- indel.data2.high[,-3]
# 
# indel.data2.high <- dcast(indel.data2.high, IPR ~ drug, value.var = "mean.ratio.bc.drug.conc")
# 
# 
# gghighlight_point(indel.data2.high, aes(x = DMSO, y = `Vorinostat (SAHA, MK0683)`), `Vorinostat (SAHA, MK0683)` - DMSO > 0.1) +
#   geom_abline(intercept = 0, slope = 1) +
#   geom_abline(intercept = 0.1, slope = 1, linetype = "dashed") +
#   geom_abline(intercept = - 0.1, slope = 1, linetype = "dashed") +
#   geom_text(aes(x = 0.4, y = 0.32, label = "-10% efficiency", angle = 35)) +
#   geom_text(aes(x = 0.4, y = 0.52, label = "+10% efficiency", angle = 35)) +
#   scale_x_continuous(limits = c(0.25, 1)) +
#   scale_y_continuous(limits = c(0.25, 1)) +
#   labs(title = "Efficiency compared to DMSO for each IPR") + 
# 
# # Make a beeswarm plot with alternative colors for outliers based on chi square scores
# ggplot_custom(data = indel.data) +
#   geom_quasirandom(mapping = 
#                      aes(x = reorder(IPR, order), y = logratio.mean, 
#                          colour = ifelse(p.value > 0.05,
#                                          "non-outlier","outlier")), alpha = 0.5) + 
#   theme(axis.text.x = element_text(angle = 90, hjust = 1.0, vjust = 0)) + 
#   ylab("log2(+1/-7 ratio)") + xlab("IPR") + 
#   labs(title = "Outlier plot", colour = "Outlier based on p value < 0.05") + 
#   scale_color_manual(values=c("#999999", "#E69F00"))
# 
# 
# 
# # Boxplot of logratio 
# indel.data$cluster <- "Active Promoter/Enhancer" 
# indel.data$cluster[indel.data$order == "3" | 
#                       indel.data$order == "4"] <- "H3K9me2/3 Domain"
# indel.data$cluster[indel.data$order == "5" | 
#                       indel.data$order == "6" |
#                       indel.data$order == "7" | 
#                       indel.data$order == "8"] <- "Active Gene Body"
# indel.data$cluster[indel.data$order == "9" | 
#                       indel.data$order == "10" |
#                       indel.data$order == "11" | 
#                       indel.data$order == "12"] <- "LAD"
# indel.data$cluster[indel.data$order == "13" | 
#                       indel.data$order == "14"] <- "No Chromatin Marks"
# indel.data$cluster[indel.data$order == "15" | 
#                       indel.data$order == "16" |
#                       indel.data$order == "17" | 
#                       indel.data$order == "18"] <- "H3K27me3 Domain"
# 
# ggplot_custom(data = indel.data[indel.data$drug != "DMSO",],
#        aes(x = reorder(IPR, order),
#            y = efficiency_zscore)) +
#   geom_quasirandom(color = ifelse(indel.data[indel.data$drug != "DMSO",]$efficiency_zscore > 2 | 
#                                     indel.data[indel.data$drug != "DMSO",]$efficiency_zscore < -2, 
#                                   "#343a40", "#6c757d")) +
#   ylab("MMEJ score")+
#   scale_fill_brewer(palette = "Pastel2")+
#   xlab("") +
#   +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1.0, vjust = 0))+
#   theme(axis.title.x = element_blank()) +
#   coord_flip()
# 
# # Are the logratios of the different IPR clusters different?
# indel.data2$int <- "1"
# indel.data2$int[indel.data2$order >= 9] <- "2"
# indel.data2$logratio <- ave(indel.data2$logratio, 
#                             indel.data2$IPR, 
#                             indel.data2$rep, 
#                             FUN = function(x) mean(x))
# indel.data2 <- indel.data2 %>% dplyr::select(rep, logratio, int, IPR) %>% unique()
# indel.data2$mean <- ave(indel.data2$logratio,
#                         indel.data2$int, 
#                         indel.data2$rep,
#                         FUN = function(x) mean(x))
# indel.data2$sd <- ave(indel.data2$logratio, 
#                       indel.data2$int, 
#                       indel.data2$rep,
#                       FUN = function(x) sd(x))
# indel.data2$p.value <- t.test(indel.data2$mean[indel.data2$int == 1], indel.data2$mean[indel.data2$int == 2])$p.value
# indel.data2$mean.bio <- ave(indel.data2$mean,
#                         indel.data2$int, 
#                         FUN = function(x) mean(x))
# indel.data2$sd.bio <- ave(indel.data2$logratio, 
#                       indel.data2$int, 
#                       FUN = function(x) sd(x))
# 
# 
# # Boxplot of efficiencies normalized
# ggplot_custom(data = indel.data[indel.data$drug == "DMSO",]) +
#   geom_boxplot(mapping = aes(x = reorder(IPR,order), y = efficiency.platenorm)) + 
#   theme(axis.text.x = element_text(angle = 90, hjust = 1.0, vjust = 0)) + 
#   labs(title = "Efficiency distribution per IPR after normalization") 
# 
# # Beeswarm plot of efficiencies
# ggplot_custom(data = indel.data) +
#   geom_quasirandom(mapping = 
#                      aes(x = reorder(IPR,order), y = efficiency.mean, 
#                          colour = ifelse(p.value > 0.05,
#                                          "non-outlier","outlier"))) + 
#   theme(axis.text.x = element_text(angle = 90, hjust = 1.0, vjust = 0)) + 
#   ylab("efficiency") + xlab("IPR") + labs(title = "Efficiency plot, outliers (based on logratio) in yellow", colour = "Logratio outlier based on p value < 0.05") + scale_color_manual(values=c("#999999", "#E69F00"))
# 
# 
# # Make a loop of plots, plotting the ratio per drug target group together with DMSO
# for (i in unique(indel.data$target)) {
#   data <- indel.data[indel.data$target == i | indel.data$target == "Negative Control", ]
#   p <- ggplot_custom(data = data) +
#     geom_quasirandom(mapping = aes(x = reorder(IPR,order), y = MMEJ_zscore, colour = target), alpha = 0.8, dodge.width = -0.5) + 
#     theme(axis.text.x = element_text(angle = 90, hjust = 1.0, vjust = 0))+ 
#     ylab("log2(+1/-7 ratio)") + xlab("IPR")+ labs(title= paste("logratio of",i, "compared to DMSO"))
#   print(p)
# }
# 
# 
# # Aurora Kinase only
# indel.data.med <- indel.data[indel.data$concentration == "1um",]
# aurora.dmso <- indel.data.med[indel.data.med$drug == "DMSO" | indel.data.med$target == "Aurora Kinase",]
# aurora.dmso$target <- factor(aurora.dmso$target, levels = c("Negative Control", "Aurora Kinase"))
# ggplot_custom(data =  aurora.dmso) +
#     geom_quasirandom(aes(x = reorder(IPR,order), y = MMEJ_zscore, colour = target, group = target), 
#                      alpha = 0.8, dodge.width = -0.5, width = 0.1) + 
#   scale_colour_brewer(palette = "Set2")+
#   coord_flip()+
#   theme(axis.title.y = element_blank())+
#     ylab("Change log2(+1/-7 ratio)")+
#   theme(text = element_text(size = 14))+
#   geom_hline(yintercept = 1, linetype = "dashed", alpha = 0.5)+
#   theme_classic2()
# 
# 
# # Decitabine only
# decitabine.dmso <- indel.data[indel.data$drug == "DMSO" | 
#                                 indel.data$drug == "Decitabine",]
# decitabine.dmso$drug <- factor(decitabine.dmso$drug, levels = c("DMSO", "Decitabine"))
# decitabine.dmso$concentration <- factor(decitabine.dmso$concentration, levels = c("100nm", "1um", "10um"))
# 
# ggplot_custom(decitabine.dmso, aes(x = reorder(IPR,order), 
#                             y = MMEJ_zscore, 
#                             colour = drug, group = drug,
#                             dodge.width = -0.5,
#                             width = 0.1)) +
#     geom_quasirandom() + 
#   scale_colour_brewer(palette = "Set2") +
#   coord_flip() +
#   theme(axis.title.y = element_blank()) +
#   ylab("MMEJ z-score") +
#   xlab("") +
#   theme(text = element_text(size = 14)) +
#   geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5) +
#    facet_wrap(~concentration)
# 
# # HDACs (efficiency and logratio)
# hdac.dmso <- indel.data[indel.data$drug == "Vorinostat (SAHA, MK0683)"|
#                           indel.data$drug == "Givinostat (ITF2357)"|
#                           indel.data$drug == "PCI-24781 (Abexinostat)"|
#                           indel.data$drug == "AR-42"|
#                           indel.data$drug == "Scriptaid ",]
# hdac.dmso <- hdac.dmso[hdac.dmso$concentration == "1um",]
# 
# hdac.dmso$MMEJ_zscore <- ave(hdac.dmso$MMEJ_zscore, 
#                              hdac.dmso$IPR, hdac.dmso$drug,
#                              FUN = function(x) mean(x))
# hdac.dmso$efficiency_zscore <- ave(hdac.dmso$efficiency_zscore, 
#                                     hdac.dmso$IPR, hdac.dmso$drug,
#                                     FUN = function(x) mean(x))
# 
# 
# hdac.dmso <- hdac.dmso %>% dplyr::select(drug, MMEJ_zscore, 
#                                   efficiency_zscore, order, 
#                                   IPR) %>% unique()
# hdac.dmso$mean <- ave(hdac.dmso$MMEJ_zscore, hdac.dmso$IPR,
#                       FUN = function(x) mean(x))
# hdac.dmso$mean2 <- ave(hdac.dmso$efficiency_zscore, hdac.dmso$IPR,
#                       FUN = function(x) mean(x))
# 
# ggplot_custom() +
#   geom_bar(data = hdac.dmso %>%
#              dplyr::select(mean, IPR, order) %>%
#              unique(), stat="identity", aes(x =  reorder(IPR,order), y = mean, alpha = 0.2)) +
#   geom_point(data = hdac.dmso, aes(x = reorder(IPR,order), y = MMEJ_zscore, color = drug)) + 
#   scale_colour_brewer(palette = "Set2")+
#   coord_flip()+
#   theme(axis.title.y = element_blank())+
#   ylab("MMEJ z-score")+
#   xlab("") +
#   theme(text = element_text(size = 14))+
#   
# 
# ggplot_custom() +
#   geom_bar(data = hdac.dmso %>%
#              dplyr::select(mean2, IPR, order) %>%
#              unique(), stat="identity", aes(x =  reorder(IPR,order), y = mean2, alpha = 0.2)) +
#   geom_point(data = hdac.dmso, aes(x = reorder(IPR,order), y = efficiency_zscore, color = drug)) + 
#   scale_colour_brewer(palette = "Set2")+
#   coord_flip()+
#   theme(axis.title.y = element_blank())+
#   ylab("efficiency z-score")+
#   xlab("") +
#   theme(text = element_text(size = 14))+
#   
# 
# # Statistical significance? Is IPR 17 different?
# anova <- aov(MMEJ_zscore ~ IPR, data = hdac.dmso)
# summary.aov(anova)
# tukey <- TukeyHSD(anova)
# 
# # Make plots for all HDACs at the three concentrations
# indel.data$concentration <- factor(indel.data$concentration, levels = c("100nm", "1um", "10um"))
# ggplot_custom(indel.data %>%
#          filter(target == "HDAC" | drug == "DMSO"),
#        aes(x = reorder(IPR, order), y = efficiency_zscore, color = target)) +
#   geom_quasirandom(dodge.width = 0.75) +
#   geom_boxplot(position = position_dodge(0.75), alpha = 0.4) +
#   
#   xlab("") +
#   scale_color_manual(values = colors_diverse) +
#   facet_wrap(~concentration) +
#   coord_flip()
# 
# # only at the specific domains
# indel.data$cluster2 <- "open" 
# indel.data$cluster2[indel.data$order == "9" | 
#                       indel.data$order == "10" |
#                       indel.data$order == "11" | 
#                       indel.data$order == "12" |
#                      indel.data$order == "13" | 
#                       indel.data$order == "14" |
#                      indel.data$order == "15" | 
#                       indel.data$order == "16" |
#                       indel.data$order == "17" | 
#                       indel.data$order == "18"] <- "condensed"
# 
# # Include detailed HDAC annotation
# hdac_annotation <- read.csv2("/DATA/usr/m.trauernicht/projects/EpiScreen/files_scripts/HDAC_categories.csv") %>%
#   dplyr::select(drug, Categorie)
# indel.data.hdac <- indel.data %>%
#   filter(target == "HDAC" | drug == "DMSO")
# indel.data.hdac <- merge(indel.data.hdac, hdac_annotation, all = T)
# 
# ggplot_custom(indel.data.hdac[!is.na(indel.data.hdac$concentration),] %>%
#          filter(Categorie %in% c("HDAC1", "HDAC3", "DMSO")),
#        aes(x = Categorie, y = efficiency_zscore, color = cluster2)) +
#   geom_quasirandom(dodge.width = 0.75) +
#   geom_boxplot(position = position_dodge(0.75), alpha = 0.4) +
#   
#   theme(axis.text.x = element_text(angle = 90, hjust = 1.0, vjust = 0.5)) + 
#   xlab("") +
#   scale_color_manual(values = colors_diverse) +
#   facet_wrap(~concentration)
```


